export enum GroupTitle {
    Power = 'Power',
    LifeSupport = 'LifeSupport',
    Structure = 'Structure',
    Mobility = 'Mobility',
    Production = 'Production',
    Control = 'Control',
    Weapons = 'Weapons',
    Mechanical = 'Mechanical',
    Other = 'Other',
}

export const BLOCK_GROUPS = [
    {
        priority: 1,
        title: GroupTitle.Power,
        types: [
            'BatteryBlock/.*',
            'Reactor/.*',
            'SolarPanel/.*',
        ],
    },
    {
        priority: 1,
        title: GroupTitle.LifeSupport,
        types: [
            'AirVent/.*',
            'AirtightHangarDoor/.*',
            'AirtightSlideDoor/.*',
            'Cockpit/.*PassengerSeat.*',
            'CryoChamber/.*',
            'Door/.*',
            'InteriorLight/.*',
            'MedicalRoom/.*',
            'OxygenTank/.*',
            'ReflectorLight/.*',
            'SoundBlock/.*',
            'TextPanel/.*',
        ],
    },
    {
        priority: 1,
        title: GroupTitle.Structure,
        types: [
            'CargoContainer/.*',
            'Conveyor/.*',
            'CubeBlock/.*Armor.*',
            'CubeBlock/.*Catwalk.*',
            'CubeBlock/.*CoverWall.*',
            'CubeBlock/.*InteriorWall.*',
            'CubeBlock/.*LargeInteriorPillar.*',
            'CubeBlock/.*LargeRamp.*',
            'CubeBlock/.*LargeStairs.*',
            'CubeBlock/.*Window.*',
            'Decoy/.*',
            'Passage/.*',
        ],
    },
    {
        priority: 1,
        title: GroupTitle.Mobility,
        types: [
            'Gyro/.*',
            'JumpDrive/.*',
            'LandingGear/.*',
            'Parachute/.*',
            'ShipConnector/.*',
            'Thrust/.*',
            'Wheel/.*',
        ],
    },
    {
        priority: 1,
        title: GroupTitle.Production,
        types: [
            'Assembler/.*',
            'OxygenFarm/.*',
            'OxygenGenerator/.*',
            'Refinery/.*',
            'UpgradeModule/.*',
        ],
    },
    {
        priority: 1,
        title: GroupTitle.Control,
        types: [
            'Beacon/.*',
            'ButtonPanel/.*',
            'CameraBlock/.*',
            'Cockpit/.*Cockpit.*',
            'ConveyorSorter/.*',
            'LaserAntenna/.*',
            'MyProgrammableBlock/.*',
            'Projector/.*',
            'RadioAntenna/.*',
            'RemoteControl/.*',
            'SensorBlock/.*',
            'TerminalBlock/.*',
            'TimerBlock/.*',
        ],
    },
    {
        priority: 1,
        title: GroupTitle.Weapons,
        types: [
            'InteriorTurret/.*',
            'LargeGatlingTurret/.*',
            'LargeMissileTurret/.*',
            'SmallMissileLauncher/.*',
            'Warhead/.*',
        ],
    },
    {
        priority: 1,
        title: GroupTitle.Mechanical,
        types: [
            'Collector/.*',
            'ConveyorConnector/.*',
            'Drill/.*',
            'ExtendedPistonBase/.*',
            'GravityGenerator/.*',
            'GravityGeneratorSphere/.*',
            'MergeBlock/.*',
            'MotorAdvancedRotor/.*',
            'MotorAdvancedStator/.*',
            'MotorRotor/.*',
            'MotorStator/.*',
            'OreDetector/.*',
            'PistonTop/.*',
            'ShipGrinder/.*',
            'ShipWelder/.*',
            'SpaceBall/.*',
        ],
    },
    {
        priority: 0,
        title: GroupTitle.Other,
        types: [
            '.*',
        ],
    },

]
