// TODO: Create API and get these values dynamically.

// var db = db.getSiblingDB('default')
// var cursor = db.blueprints.aggregate([
//     { $match: { steam: {$exists: true} } },
//     { $group: { _id: "$steam.author.title", count: { $sum: 1 } } },
//     { $match: { count: {$gte: 10} } },
//     { $sort : { count: -1 } },
// ])
// while(cursor.hasNext()) printjson(cursor.next())

export const AUTOCOMPLETE_AUTHORS = [
    { value: "Eddy", amount: 417 },
    { value: "Lord Wraith SOL3", amount: 263 },
    { value: "PrimoSuperT", amount: 240 },
    { value: "CA-[23rdVA]1stLt. Tiger", amount: 204 },
    { value: "WisdomTooth8", amount: 203 },
    { value: "Drakiシ", amount: 189 },
    { value: "Lystent", amount: 188 },
    { value: "dvlwsere", amount: 183 },
    { value: "Alien 480", amount: 182 },
    { value: "McTec Ind.", amount: 180 },
    { value: "Spite", amount: 170 },
    { value: "MrEvan312", amount: 170 },
    { value: "LeapedSiren97", amount: 168 },
    { value: "Dar Kovalord", amount: 166 },
    { value: "[WTFH] ragnar_greymane", amount: 166 },
    { value: "[Havanna RP] [TF] Lord Mexium", amount: 158 },
    { value: "Luvstruckmango", amount: 158 },
    { value: "SpetS", amount: 157 },
    { value: "Bruce LeedleLeedleLeedleLee", amount: 157 },
    { value: "High Ground", amount: 154 },
    { value: "jk", amount: 154 },
    { value: "AlonE", amount: 146 },
    { value: "Spaceman Spiff", amount: 145 },
    { value: "Saladin", amount: 144 },
    { value: "dhartvault", amount: 138 },
    { value: "321_puleknow", amount: 133 },
    { value: "Malacanth", amount: 132 },
    { value: "Purrfect-Blinky", amount: 128 },
    { value: "TellerTactGaming", amount: 127 },
    { value: "DragoF1sh", amount: 125 },
    { value: "Hull Breach", amount: 125 },
    { value: "Flatulent_Moth", amount: 125 },
    { value: "Sauna", amount: 122 },
    { value: "Nexar", amount: 121 },
    { value: "JukaBALA", amount: 119 },
    { value: "NordicBeast", amount: 114 },
    { value: "JD.Horx", amount: 112 },
    { value: "Enduar", amount: 110 },
    { value: "Samerrie", amount: 110 },
    { value: "The Shadow", amount: 110 },
    { value: "k_medlock", amount: 109 },
    { value: "Dr. Skeeter", amount: 109 },
    { value: "Helratz", amount: 108 },
    { value: "KawaiLogic", amount: 108 },
    { value: "Elfi Wolfe", amount: 107 },
    { value: "Marcelo ACFM", amount: 106 },
    { value: "☣▬ᗰᗩ᙭Iᗰᕮ7080▬☣", amount: 105 },
    { value: "Major Jon", amount: 104 },
    { value: "BlackArmor", amount: 103 },
    { value: "JETNET", amount: 103 },
    { value: "Yuna", amount: 102 },
    { value: "PyreStarite", amount: 101 },
    { value: "[Civil]", amount: 100 },
    { value: "mahtrok", amount: 100 },
    { value: "MoonAppleSeed", amount: 98 },
    { value: "sauron2012", amount: 98 },
    { value: "Mattacon", amount: 96 },
    { value: "(STRM)TheIronWolf45", amount: 96 },
    { value: "Tachyon particles", amount: 94 },
    { value: "Bad Dain Bramage", amount: 93 },
    { value: "Mad-Catcher", amount: 93 },
    { value: "Silvro", amount: 93 },
    { value: "GopeScope", amount: 89 },
    { value: "Lord Damp Nut", amount: 89 },
    { value: "5URG3", amount: 89 },
    { value: "FireStorm", amount: 89 },
    { value: "mhwyoshi", amount: 88 },
    { value: "OctoMoose", amount: 88 },
    { value: "CGT-CREATIVE", amount: 87 },
    { value: "Kiyashi", amount: 87 },
    { value: "Beesoldier", amount: 87 },
    { value: "StreamBG", amount: 86 },
    { value: "Whiplash141", amount: 86 },
    { value: "Const", amount: 85 },
    { value: "Brubaker", amount: 84 },
    { value: "Blue Moon", amount: 84 },
    { value: "PeterHammerman", amount: 84 },
    { value: "Regnion", amount: 84 },
    { value: "Wolf", amount: 82 },
    { value: "LeonserGT", amount: 81 },
    { value: "nelnia", amount: 81 },
    { value: "[FP]Anthony7094", amount: 80 },
    { value: "Oisin", amount: 80 },
    { value: "micpez93", amount: 79 },
    { value: "polaarbunnygirl", amount: 79 },
    { value: "boanerges929", amount: 78 },
    { value: "FlocK", amount: 77 },
    { value: "...", amount: 77 },
    { value: "JoeTheAntiPro", amount: 77 },
    { value: "meiler.berlin1", amount: 76 },
    { value: "Lord Commissar", amount: 76 },
    { value: "SuicideNeil", amount: 76 },
    { value: "Clockwork168", amount: 75 },
    { value: "Duke of Lorraine", amount: 75 },
    { value: "FN-2197", amount: 74 },
    { value: "boostercc2000", amount: 74 },
    { value: "kevd42", amount: 73 },
    { value: "Alpha-5", amount: 73 },
    { value: "jura7", amount: 73 },
    { value: "神崎峯政", amount: 72 },
    { value: "AfgooeyKeef", amount: 72 },
    { value: "JP_2793", amount: 72 },
    { value: "Cypress", amount: 71 },
    { value: "mastodont", amount: 71 },
    { value: "UNOWHO", amount: 71 },
    { value: "Whaddageek", amount: 70 },
    { value: "SS Obersturmsw@gfuhrer", amount: 70 },
    { value: "Holford411", amount: 70 },
    { value: "gundam2jimmy", amount: 70 },
    { value: "Faely", amount: 69 },
    { value: "the lone_archer", amount: 69 },
    { value: "Deceti", amount: 69 },
    { value: "Ventus Pri", amount: 69 },
    { value: "DonCoyote", amount: 69 },
    { value: "Space Kitten", amount: 69 },
    { value: "warrior1609", amount: 68 },
    { value: "ChocoCrispi", amount: 68 },
    { value: "Ashley Cinders", amount: 68 },
    { value: "creeper king 82", amount: 67 },
    { value: "SkekSel the Engineer", amount: 67 },
    { value: "Doctor Budgie", amount: 66 },
    { value: "Rakshasa", amount: 66 },
    { value: "Keq", amount: 66 },
    { value: "Nuclear Pyromaniac", amount: 65 },
    { value: "remethep", amount: 65 },
    { value: "LeeTheFlea", amount: 65 },
    { value: "Dan2D3D", amount: 64 },
    { value: "w4stedspace", amount: 64 },
    { value: "FIDA", amount: 63 },
    { value: "Pathagarus", amount: 62 },
    { value: "朝倉 hara/nagi", amount: 62 },
    { value: "bennettboat", amount: 62 },
    { value: "Malmhrid", amount: 61 },
    { value: "jimlore78", amount: 61 },
    { value: "Mighty Brankor", amount: 61 },
    { value: "dawntemplers", amount: 61 },
    { value: "Deathlok-L17", amount: 61 },
    { value: "Code_Alpha", amount: 61 },
    { value: "huiyao117", amount: 61 },
    { value: "Commander Rotal", amount: 61 },
    { value: "Rick Marten [ZCOM]", amount: 60 },
    { value: "ronidude", amount: 60 },
    { value: "jinneyeh", amount: 60 },
    { value: "EctoSage", amount: 60 },
    { value: "Keeper", amount: 59 },
    { value: "AutoMcDonough", amount: 59 },
    { value: "Parabellum", amount: 59 },
    { value: "Kerian Halcyon", amount: 58 },
    { value: "IvanZPG", amount: 58 },
    { value: "Jeffrey Epstein", amount: 58 },
    { value: "Venom415", amount: 58 },
    { value: "DarkDragon", amount: 57 },
    { value: "Tom-Babz", amount: 57 },
    { value: "xenolego", amount: 57 },
    { value: "Eternal Dolphin", amount: 57 },
    { value: "Sergeant Kelly", amount: 56 },
    { value: "永恒帝国工程师", amount: 56 },
    { value: "Mork", amount: 56 },
    { value: "Prellentor", amount: 55 },
    { value: "Meridius_IX / Lucas", amount: 55 },
    { value: "Spirit Warden", amount: 55 },
    { value: "TRAV.", amount: 54 },
    { value: "Brisingr Drake", amount: 54 },
    { value: "Sjelherre", amount: 54 },
    { value: "X3:WMZ", amount: 54 },
    { value: "Spectre25", amount: 54 },
    { value: "Shipmaster_Crook", amount: 54 },
    { value: "zalex 🎄", amount: 53 },
    { value: "syphersox", amount: 53 },
    { value: "Nyran", amount: 53 },
    { value: "Citizen_Soldier", amount: 53 },
    { value: "Bandana Dee 25", amount: 53 },
    { value: "big doggy 2", amount: 52 },
    { value: "lolomanx", amount: 52 },
    { value: "Superman", amount: 52 },
    { value: "Nick Gray", amount: 52 },
    { value: "Torgenator", amount: 51 },
    { value: "Wildcard", amount: 51 },
    { value: "Enigmus", amount: 51 },
    { value: "parkasever", amount: 51 },
    { value: "DerMakrat", amount: 51 },
    { value: "cptsavarus", amount: 51 },
    { value: "xxkillerlordxx", amount: 51 },
    { value: "Solus454", amount: 51 },
    { value: "Caballo Loco", amount: 51 },
    { value: "Flygtur", amount: 51 },
    { value: "Nazz27", amount: 50 },
    { value: "IsEstredundant", amount: 50 },
    { value: "volgraza", amount: 50 },
    { value: "Mr_fireman", amount: 49 },
    { value: "1095058782", amount: 49 },
    { value: "Aragath", amount: 49 },
    { value: "Pablo Escobar", amount: 49 },
    { value: "Gandur", amount: 49 },
    { value: "[WN] xPhantom GenesisX", amount: 49 },
    { value: "akaalexandermax", amount: 49 },
    { value: "War Wolf", amount: 49 },
    { value: "frogboy1320", amount: 48 },
    { value: "Dragon_Gornamer", amount: 48 },
    { value: "Nekron910", amount: 48 },
    { value: "kris220b", amount: 48 },
    { value: "Zhiila", amount: 48 },
    { value: "FSEK_Raver94194 GER", amount: 48 },
    { value: "Defiance053", amount: 47 },
    { value: "Mr B.", amount: 47 },
    { value: "j0n0nym0us", amount: 47 },
    { value: "Ninjaxtreme04", amount: 47 },
    { value: "Arara", amount: 47 },
    { value: "Tiberius", amount: 47 },
    { value: "Matthew", amount: 47 },
    { value: "Papple2", amount: 47 },
    { value: "_unauthorised_", amount: 47 },
    { value: "Embrace Space", amount: 47 },
    { value: "Admiral_Redz", amount: 46 },
    { value: "Jeager-Gon", amount: 46 },
    { value: "The Star Core", amount: 46 },
    { value: "rickw_sec", amount: 46 },
    { value: "Dumbbell Dan", amount: 45 },
    { value: "mr.e.r.edwards", amount: 45 },
    { value: "fabricator77", amount: 45 },
    { value: "Ciel-PMM", amount: 45 },
    { value: "fillopygeesi", amount: 45 },
    { value: "Tiger", amount: 45 },
    { value: "wolfen7lada", amount: 45 },
    { value: "[Dolt] Nuri", amount: 44 },
    { value: "Imperito", amount: 44 },
    { value: "MadBillyBlack", amount: 44 },
    { value: "Uranius Crack", amount: 44 },
    { value: "C.DEF", amount: 44 },
    { value: "Tatz", amount: 43 },
    { value: "RogueDelta", amount: 43 },
    { value: "SGT_MAJOR_FISH", amount: 43 },
    { value: "Foxtecy YT", amount: 43 },
    { value: "DoctorGroot", amount: 43 },
    { value: "Ruby", amount: 43 },
    { value: "🌹 Ruby Rose 🌹", amount: 43 },
    { value: "YoYo_Pa", amount: 43 },
    { value: "TheTreeman", amount: 43 },
    { value: "Alysius", amount: 43 },
    { value: "celgb", amount: 43 },
    { value: "Wraithcutter", amount: 43 },
    { value: "Scarlett", amount: 43 },
    { value: "Extevious", amount: 43 },
    { value: "ExoticMango17", amount: 43 },
    { value: "FILIN", amount: 42 },
    { value: "Killerjoe-Cowboy", amount: 42 },
    { value: "DtDrag", amount: 42 },
    { value: "Endar949", amount: 42 },
    { value: "Vomsay", amount: 42 },
    { value: "Sunoko", amount: 42 },
    { value: "General Mega", amount: 42 },
    { value: "Ripps", amount: 42 },
    { value: "Jonnyhawkeye", amount: 42 },
    { value: "Herlock", amount: 42 },
    { value: "Eliseu do Brasil", amount: 42 },
    { value: "jino", amount: 42 },
    { value: "Mikeangel", amount: 42 },
    { value: "Cartwheel800", amount: 41 },
    { value: "Fade Sevar", amount: 41 },
    { value: "Dastex", amount: 41 },
    { value: "High Lord Baron", amount: 41 },
    { value: "Captain Jack", amount: 41 },
    { value: "Quartofel", amount: 41 },
    { value: "Fox", amount: 41 },
    { value: "Skie Silversong", amount: 41 },
    { value: "Loptyeir", amount: 40 },
    { value: "Caféine", amount: 40 },
    { value: "Lazarus", amount: 40 },
    { value: "Drunken British Chap", amount: 40 },
    { value: "| n f a m o u s", amount: 40 },
    { value: "BOBspiritus", amount: 40 },
    { value: "Johnathan", amount: 40 },
    { value: "GrumpyJedi3", amount: 39 },
    { value: "Valkyrie Ice", amount: 39 },
    { value: "Captain X (PhoenixX)", amount: 39 },
    { value: "MurlocJoe", amount: 39 },
    { value: "Nostrian 99", amount: 39 },
    { value: "Bilgeworth", amount: 39 },
    { value: "Masterchief A10™", amount: 39 },
    { value: "Mialll_", amount: 38 },
    { value: "DarkHoodness", amount: 38 },
    { value: "Jatemputz", amount: 38 },
    { value: "Not Scared", amount: 38 },
    { value: "EnjoyCoke", amount: 38 },
    { value: "Thasrion", amount: 38 },
    { value: "BlueTron301", amount: 38 },
    { value: "Elachi Dance Party", amount: 38 },
    { value: "Sovice", amount: 38 },
    { value: "RobskuWitteWel", amount: 37 },
    { value: "Tharatan", amount: 37 },
    { value: "Demize74", amount: 37 },
    { value: "ZJE123", amount: 37 },
    { value: "terran29", amount: 37 },
    { value: "PopPyZaa555", amount: 37 },
    { value: "retech", amount: 37 },
    { value: "CanisDirus", amount: 37 },
    { value: "theJacenOne", amount: 37 },
    { value: "[SDL] Winfield", amount: 37 },
    { value: "crazysteve887", amount: 36 },
    { value: "Venixer", amount: 36 },
    { value: "AcheKALo", amount: 36 },
    { value: "FoxtrotDelta", amount: 36 },
    { value: "Endington", amount: 36 },
    { value: "Artika", amount: 36 },
    { value: "Splitsie", amount: 36 },
    { value: "Alex \'Blade\' Prower", amount: 36 },
    { value: "Skeloton", amount: 36 },
    { value: "phoenixtalon", amount: 36 },
    { value: "Auren", amount: 36 },
    { value: "Taidyr", amount: 36 },
    { value: "Lord_Anubis", amount: 36 },
    { value: "Emperor Palpatine (Darek)", amount: 36 },
    { value: "Killerbee77", amount: 36 },
    { value: "Boz", amount: 35 },
    { value: "Lengueni", amount: 35 },
    { value: "Fuhrer Legitglenn™", amount: 35 },
    { value: "[BKNE] UrbanMech", amount: 35 },
    { value: "the_educater", amount: 35 },
    { value: "H (UwU)", amount: 35 },
    { value: "GEK Vengeful", amount: 35 },
    { value: "Piss Cakehole", amount: 35 },
    { value: "Taiko", amount: 35 },
    { value: "Mojo", amount: 34 },
    { value: "RangeRunner", amount: 34 },
    { value: "sg-1homeworld", amount: 34 },
    { value: "gorinich_044", amount: 34 },
    { value: "Riz", amount: 34 },
    { value: "Rocketeer115", amount: 34 },
    { value: "[FR]HunterHawks(Wolf)", amount: 34 },
    { value: "Korvatus Klok", amount: 34 },
    { value: "Sir Valentine", amount: 34 },
    { value: "Dentistman", amount: 34 },
    { value: "Awesome Opossum", amount: 34 },
    { value: "budisourdog", amount: 34 },
    { value: "Pariah Devalis", amount: 33 },
    { value: "KhydroDjent", amount: 33 },
    { value: "HybridZero", amount: 33 },
    { value: "Dolan", amount: 33 },
    { value: "Literally God", amount: 33 },
    { value: "$ Volfoni", amount: 33 },
    { value: "noLieBowtie", amount: 33 },
    { value: "Baalrog", amount: 33 },
    { value: "tommy_forman", amount: 33 },
    { value: "Spartacus", amount: 33 },
    { value: "Lavamoon", amount: 33 },
    { value: "Chris", amount: 33 },
    { value: "Scifi", amount: 33 },
    { value: "scorpnoire", amount: 33 },
    { value: "Neraph", amount: 33 },
    { value: "Angel", amount: 33 },
    { value: "RelicSage", amount: 33 },
    { value: "geeklund", amount: 33 },
    { value: "Maverick", amount: 32 },
    { value: "Eisdialer", amount: 32 },
    { value: "FlingWolf", amount: 32 },
    { value: "Hemza", amount: 32 },
    { value: "Marek Moowi", amount: 32 },
    { value: "KindaPhunny", amount: 32 },
    { value: "Alec KDY", amount: 32 },
    { value: "Vagrant | John", amount: 32 },
    { value: "123", amount: 32 },
    { value: "Furry_Fox", amount: 32 },
    { value: "Genesis_ryzz", amount: 32 },
    { value: "Matt The Lost Spaceman", amount: 32 },
    { value: "Reaper", amount: 32 },
    { value: "bIrD_oF_pReY", amount: 32 },
    { value: "Captein", amount: 32 },
    { value: "Digital Soul", amount: 32 },
    { value: "Elon", amount: 32 },
    { value: "generaalsab", amount: 32 },
    { value: "william_moryguard", amount: 32 },
    { value: "shadenquest", amount: 31 },
    { value: "abordoli", amount: 31 },
    { value: "werner", amount: 31 },
    { value: "BinaryDuck", amount: 31 },
    { value: "Kimyoone", amount: 31 },
    { value: "iker IR4_YT", amount: 31 },
    { value: "Commander Kwiec", amount: 31 },
    { value: "Paul Drive", amount: 31 },
    { value: "ÆnꞀ -2onio", amount: 31 },
    { value: "WardenWolf", amount: 31 },
    { value: "XxGoingGamerXx", amount: 31 },
    { value: "vanga the tinny", amount: 31 },
    { value: "Tibrochief", amount: 31 },
    { value: "Memlapse", amount: 31 },
    { value: "halipatsui", amount: 31 },
    { value: "Goldshell", amount: 31 },
    { value: "Kreeg", amount: 31 },
    { value: "Professor Brian Cock", amount: 31 },
    { value: "maxmad", amount: 31 },
    { value: "=(e)= -=BR=- death reaper", amount: 31 },
    { value: "Qman1230", amount: 31 },
    { value: "Wedgehog", amount: 31 },
    { value: "sandosan83", amount: 30 },
    { value: "Sarekh", amount: 30 },
    { value: "☭ NorthyPark ", amount: 30 },
    { value: "azrul", amount: 30 },
    { value: "Hesterry", amount: 30 },
    { value: "FLIPPY", amount: 30 },
    { value: "Shidy", amount: 30 },
    { value: "Jim", amount: 30 },
    { value: "XIII", amount: 30 },
    { value: "[IV]_Nomat", amount: 30 },
    { value: "The Sir Rolfe", amount: 30 },
    { value: "Fleischdesigner", amount: 30 },
    { value: "Bragondorn", amount: 30 },
    { value: "Randaped", amount: 30 },
    { value: "Johnathan123YT", amount: 30 },
    { value: "SheildyMcgee", amount: 30 },
    { value: "Ayphion", amount: 30 },
    { value: "hav0kk", amount: 30 },
    { value: "终不渝", amount: 30 },
    { value: "Zach", amount: 30 },
    { value: "Mr. Midori", amount: 29 },
    { value: "Someguy Somewhere", amount: 29 },
    { value: "w.w.b", amount: 29 },
    { value: "Stoicus", amount: 29 },
    { value: "mixa444ok", amount: 29 },
    { value: "DesertStorm", amount: 29 },
    { value: "novard", amount: 29 },
    { value: "Kilroy", amount: 29 },
    { value: "soup", amount: 29 },
    { value: "OpaIon", amount: 29 },
    { value: "Aluburuier", amount: 29 },
    { value: "Fabicity", amount: 29 },
    { value: "Valitrize", amount: 29 },
    { value: "Lander1", amount: 29 },
    { value: "Viper", amount: 29 },
    { value: "White Mist", amount: 29 },
    { value: "LEOSAURE", amount: 29 },
    { value: "Gompasta", amount: 29 },
    { value: "Skitto493", amount: 29 },
    { value: "KiwiBear", amount: 29 },
    { value: "MACH Velocity", amount: 29 },
    { value: "agrimes", amount: 29 },
    { value: "Wooffe", amount: 29 },
    { value: "Tiji san", amount: 29 },
    { value: "Xura", amount: 29 },
    { value: "|>Heroin Hero<|", amount: 29 },
    { value: "Silas H. Tyler", amount: 29 },
    { value: "lolmelon3", amount: 28 },
    { value: "NaCl", amount: 28 },
    { value: "Nightshifter", amount: 28 },
    { value: "Wreckeronezero", amount: 28 },
    { value: "kitchen gun", amount: 28 },
    { value: "Ramalis", amount: 28 },
    { value: "[REF]Saquesh", amount: 28 },
    { value: "Murat", amount: 28 },
    { value: "Drakedge", amount: 28 },
    { value: "Umbreon777", amount: 28 },
    { value: "Thanatoast", amount: 28 },
    { value: "Craig P", amount: 28 },
    { value: "✌Husker54✌", amount: 28 },
    { value: "Shrouded Soul", amount: 28 },
    { value: "Beastmoder247", amount: 28 },
    { value: "Major Cuddles", amount: 28 },
    { value: "ZDuke", amount: 28 },
    { value: "ZeichenZwerg", amount: 28 },
    { value: "ALUCARD7729", amount: 28 },
    { value: "Lunar", amount: 28 },
    { value: "zachy97", amount: 28 },
    { value: "Saiima", amount: 28 },
    { value: "895245167", amount: 28 },
    { value: "Adaline", amount: 28 },
    { value: "Sektan", amount: 28 },
    { value: "Canofjuice", amount: 28 },
    { value: "luvs", amount: 28 },
    { value: "Falnore", amount: 28 },
    { value: "Alex", amount: 28 },
    { value: "Xelathia", amount: 28 },
    { value: "btaylor00744", amount: 28 },
    { value: "Moon", amount: 28 },
    { value: "SpaaaaaaceMouse", amount: 28 },
    { value: "SaltyMereKat257", amount: 28 },
    { value: "Zaƒlow", amount: 28 },
    { value: "CrimsonJupiter", amount: 27 },
    { value: "Zinwarin", amount: 27 },
    { value: "K.W. [rus]", amount: 27 },
    { value: "DuffMan", amount: 27 },
    { value: "Kasper", amount: 27 },
    { value: "HФRSEPAIN", amount: 27 },
    { value: "Namdoolb=FILTH=", amount: 27 },
    { value: "Captain Worth", amount: 27 },
    { value: "JAM8957", amount: 27 },
    { value: "Evil_Doc (Retired)", amount: 27 },
    { value: "Norrin Radd", amount: 27 },
    { value: "mrcalzon02", amount: 27 },
    { value: "jarhead", amount: 27 },
    { value: "Candicen Procella", amount: 27 },
    { value: "AikawaKizuna", amount: 27 },
    { value: "Archiviste", amount: 27 },
    { value: "Roy", amount: 27 },
    { value: "Spacebar", amount: 27 },
    { value: "id3dteen", amount: 27 },
    { value: "Bidahochi", amount: 27 },
    { value: "spiritplumber[FUG]", amount: 27 },
    { value: "Emperor Xi the Pooh", amount: 27 },
    { value: "rebellionmarch", amount: 27 },
    { value: "RT-Macr", amount: 27 },
    { value: "Zalioris", amount: 27 },
    { value: "High Templar of Allium Cepa", amount: 27 },
    { value: "Dwarf-Lord Pangolin", amount: 27 },
    { value: "Jackal Blackal", amount: 27 },
    { value: "KDMN", amount: 27 },
    { value: "Miiguelx_", amount: 27 },
    { value: "KaldariaQ", amount: 27 },
    { value: "Kuu Lightwing", amount: 27 },
    { value: "RedMar", amount: 27 },
    { value: "Bear87", amount: 26 },
    { value: "FunkyBacon", amount: 26 },
    { value: "TITAN PRIME", amount: 26 },
    { value: "LittleTimelord", amount: 26 },
    { value: "JOHNFRANKPIGEON", amount: 26 },
    { value: "Vii", amount: 26 },
    { value: "EtanchMouMout", amount: 26 },
    { value: "Commissar Cotchinsky", amount: 26 },
    { value: "Crapaud", amount: 26 },
    { value: "AlliedArmor32107-[DGI]-", amount: 26 },
    { value: "Thee Landmine Fairy", amount: 26 },
    { value: "Azzona", amount: 26 },
    { value: "Vic Viper", amount: 26 },
    { value: "Carl", amount: 26 },
    { value: "Kaptain_Kai", amount: 26 },
    { value: "Vakot[UA]", amount: 26 },
    { value: "Synchronex", amount: 26 },
    { value: "▲JosunLP©▲", amount: 26 },
    { value: "Commander Shepard", amount: 26 },
    { value: "satius", amount: 26 },
    { value: "carn1vore", amount: 26 },
    { value: "sevaryb", amount: 26 },
    { value: "OperationAngel", amount: 26 },
    { value: "Cat", amount: 26 },
    { value: "Lorbarsan", amount: 26 },
    { value: "Licensed2kill", amount: 26 },
    { value: "MrKiel", amount: 26 },
    { value: "Laurynas01", amount: 26 },
    { value: "SziCine", amount: 26 },
    { value: "Dj_Guimarães", amount: 26 },
    { value: "Yomki", amount: 26 },
    { value: "beanieaniki", amount: 26 },
    { value: "Dirk", amount: 25 },
    { value: "Hyperschnizel", amount: 25 },
    { value: "Chief", amount: 25 },
    { value: "Димыч", amount: 25 },
    { value: "Pa Chu", amount: 25 },
    { value: "Faulkril000", amount: 25 },
    { value: "Isilme", amount: 25 },
    { value: "doom", amount: 25 },
    { value: "clone.wars.hero5", amount: 25 },
    { value: "Headachypit80", amount: 25 },
    { value: "亚空间之主", amount: 25 },
    { value: "Snipes", amount: 25 },
    { value: "STARK MAMETO", amount: 25 },
    { value: "Barrio505", amount: 25 },
    { value: "John F. Kennedy", amount: 25 },
    { value: "TheSovietAggron", amount: 25 },
    { value: "Grimstock", amount: 25 },
    { value: "govrom", amount: 25 },
    { value: "Stone Cold Jane Austen", amount: 25 },
    { value: "Ph.D Composer", amount: 25 },
    { value: "SultonMRP", amount: 25 },
    { value: "Mentor_N7", amount: 25 },
    { value: "BOlek", amount: 25 },
    { value: "Hotshot", amount: 25 },
    { value: "BL8NT", amount: 25 },
    { value: "GreenNarwals", amount: 25 },
    { value: "TEGC Quantum", amount: 25 },
    { value: "Bytestorm", amount: 25 },
    { value: "PapaFreej", amount: 25 },
    { value: "Omega1102", amount: 25 },
    { value: "SilverDude", amount: 25 },
    { value: "Vollstrecker", amount: 25 },
    { value: "RaveN", amount: 25 },
    { value: "kclarke32", amount: 25 },
    { value: "RHS0", amount: 25 },
    { value: "_Nazarov7576_", amount: 25 },
    { value: "Kowalski", amount: 25 },
    { value: "ArtistX", amount: 25 },
    { value: "Skallabjorn", amount: 25 },
    { value: "Lunarjman89", amount: 25 },
    { value: "Skuzzlebutt", amount: 25 },
    { value: "Crozzo", amount: 25 },
    { value: "OneOfUs", amount: 25 },
    { value: "Ace781", amount: 25 },
    { value: "Niel", amount: 24 },
    { value: "W0lf3y", amount: 24 },
    { value: "Bumpkin_Actual", amount: 24 },
    { value: "AssassineMaxli", amount: 24 },
    { value: "makins_90", amount: 24 },
    { value: "oODekerOo", amount: 24 },
    { value: "Random Guy", amount: 24 },
    { value: "Mityenka", amount: 24 },
    { value: "Baerful", amount: 24 },
    { value: "ThiccBeard", amount: 24 },
    { value: "HellKat-76", amount: 24 },
    { value: "paralyzingNuke", amount: 24 },
    { value: "PheoniX", amount: 24 },
    { value: "Stratus", amount: 24 },
    { value: "THOMY", amount: 24 },
    { value: "MikeFox88", amount: 24 },
    { value: "Hank Jimbo", amount: 24 },
    { value: "Michael", amount: 24 },
    { value: "impending_zombie_apocalypse", amount: 24 },
    { value: "spring jordy", amount: 24 },
    { value: "PuschelSan", amount: 24 },
    { value: "ZeroDevil", amount: 24 },
    { value: "Eoin", amount: 24 },
    { value: "dragonqaz67", amount: 24 },
    { value: "RUGGER", amount: 24 },
    { value: "danogrg", amount: 24 },
    { value: "Drone185", amount: 24 },
    { value: "Riasrock", amount: 24 },
    { value: "grox0642", amount: 24 },
    { value: "Miggo", amount: 24 },
    { value: "Hombre", amount: 23 },
    { value: "Mr Happy Hammers", amount: 23 },
    { value: "Bundi The Shifter", amount: 23 },
    { value: "Dr.Craz", amount: 23 },
    { value: "EXPAND_DONG", amount: 23 },
    { value: "ARKTrooper", amount: 23 },
    { value: "CyberShot288", amount: 23 },
    { value: "(Anime Tv Guy 44)", amount: 23 },
    { value: "DON", amount: 23 },
    { value: "Partykekz", amount: 23 },
    { value: "Mantha", amount: 23 },
    { value: "FatDoBee", amount: 23 },
    { value: "Okalar_Ulosh (valarkan)", amount: 23 },
    { value: "Ghost", amount: 23 },
    { value: "FireFighter_Jeffery", amount: 23 },
    { value: "B1GGEST", amount: 23 },
    { value: "RADAR", amount: 23 },
    { value: "wikedsirnate", amount: 23 },
    { value: "AWG", amount: 23 },
    { value: "xzosimusx", amount: 23 },
    { value: "TheChuggernaut", amount: 23 },
    { value: "Thunder-Invader", amount: 23 },
    { value: "MikeTheAncient", amount: 23 },
    { value: "Opcomanderz", amount: 23 },
    { value: "AussieYT", amount: 23 },
    { value: "dreadnought", amount: 23 },
    { value: "Grass", amount: 23 },
    { value: "Herr-Doktor", amount: 23 },
    { value: "Khaste", amount: 23 },
    { value: "Noxy", amount: 23 },
    { value: "olen.a.gellein", amount: 23 },
    { value: "jebo14", amount: 23 },
    { value: "ZambyDawg", amount: 23 },
    { value: "Reaver", amount: 23 },
    { value: "SlobbishHalo", amount: 23 },
    { value: "Schwarzengel", amount: 22 },
    { value: "artemyevrus", amount: 22 },
    { value: "boosted animal", amount: 22 },
    { value: "CarbonCopy", amount: 22 },
    { value: "Captain Ed Mercer", amount: 22 },
    { value: "kerber", amount: 22 },
    { value: "the-phil", amount: 22 },
    { value: "vegecethepilot", amount: 22 },
    { value: "sirhollysworth", amount: 22 },
    { value: "iamwright16", amount: 22 },
    { value: "ApathyGates", amount: 22 },
    { value: "Eisen", amount: 22 },
    { value: "max tog", amount: 22 },
    { value: "hauda.thomas", amount: 22 },
    { value: "The Bush Wolf", amount: 22 },
    { value: "Minus.1", amount: 22 },
    { value: "Greyze", amount: 22 },
    { value: "Inigma", amount: 22 },
    { value: "xorace", amount: 22 },
    { value: "Pounce", amount: 22 },
    { value: "Kenty94", amount: 22 },
    { value: "Bismuth", amount: 22 },
    { value: "yoshino", amount: 22 },
    { value: "Wild Cards", amount: 22 },
    { value: "FigoPhoenix", amount: 22 },
    { value: "Rin ~ お疲れ", amount: 22 },
    { value: "Waipa", amount: 22 },
    { value: "Phrixos28", amount: 22 },
    { value: "Cr@zyMoose", amount: 22 },
    { value: "Hindsight2020", amount: 22 },
    { value: "Kushnir [UA]", amount: 22 },
    { value: "Reverend-Tooly", amount: 22 },
    { value: "MikeLevi316", amount: 22 },
    { value: "DOOM GODS", amount: 22 },
    { value: "ThisNthaT", amount: 22 },
    { value: "DoctorDiscord", amount: 22 },
    { value: "Trozzo", amount: 22 },
    { value: "Rush877", amount: 22 },
    { value: "GECO", amount: 22 },
    { value: "nukeguard", amount: 22 },
    { value: "A_N1ne", amount: 22 },
    { value: "Solifeaul", amount: 22 },
    { value: "SilentNinja724", amount: 22 },
    { value: "DRAGONFIRE125", amount: 22 },
    { value: "Hewlett Craphard", amount: 22 },
    { value: "KAMRAD", amount: 22 },
    { value: "Pennywise", amount: 22 },
    { value: "davidsupermantv", amount: 22 },
    { value: "Svinom", amount: 22 },
    { value: "Seric Abis", amount: 21 },
    { value: "MML", amount: 21 },
    { value: "Captain", amount: 21 },
    { value: "zetkuba99", amount: 21 },
    { value: "RA9", amount: 21 },
    { value: "Phoenix", amount: 21 },
    { value: "Grinko", amount: 21 },
    { value: "blackwatch", amount: 21 },
    { value: "Taishiryu", amount: 21 },
    { value: "Kelevra", amount: 21 },
    { value: "glenn52", amount: 21 },
    { value: "Johnathan Wack", amount: 21 },
    { value: "Tessa Volkanvir", amount: 21 },
    { value: "Rob320", amount: 21 },
    { value: "ninjanuruku", amount: 21 },
    { value: "wu.will.china", amount: 21 },
    { value: "IBen01", amount: 21 },
    { value: "DigglerJr", amount: 21 },
    { value: "arturkandla", amount: 21 },
    { value: "Darth Vecthan", amount: 21 },
    { value: "AstroByte_YT", amount: 21 },
    { value: "Neiz 桜", amount: 21 },
    { value: "Pred", amount: 21 },
    { value: "WolfoftheWest", amount: 21 },
    { value: "omega_kt4", amount: 21 },
    { value: "DEATH AWAKENED", amount: 21 },
    { value: "Meepermcmeep", amount: 21 },
    { value: "Yuka", amount: 21 },
    { value: "Dan", amount: 21 },
    { value: "Lt.Starbound", amount: 21 },
    { value: "gizmo-7738", amount: 21 },
    { value: "Cool plays", amount: 21 },
    { value: "sharptile", amount: 21 },
    { value: "Scapegoat", amount: 21 },
    { value: "WanderingEngineer", amount: 21 },
    { value: "Executer Inside", amount: 21 },
    { value: "The Warden", amount: 21 },
    { value: "MrTango", amount: 21 },
    { value: "tOPIV", amount: 21 },
    { value: "EEE AI", amount: 21 },
    { value: "Carbonschmied", amount: 21 },
    { value: "Bman", amount: 21 },
    { value: "Vechs", amount: 21 },
    { value: "XFE_studio", amount: 21 },
    { value: "Thor117", amount: 21 },
    { value: "Sergio", amount: 21 },
    { value: "愤怒的大米沙", amount: 21 },
    { value: "♠Troll-Kiuby♠", amount: 21 },
    { value: "UNDERTAKER 67", amount: 20 },
    { value: "mou", amount: 20 },
    { value: "PGI Xx HunterxX", amount: 20 },
    { value: "PYROMAN", amount: 20 },
    { value: "Weebgod of Warplanes", amount: 20 },
    { value: "qb4k", amount: 20 },
    { value: "SpaceGameManiac", amount: 20 },
    { value: "SpaceX24", amount: 20 },
    { value: "buster5300", amount: 20 },
    { value: "Slaine", amount: 20 },
    { value: "Apone", amount: 20 },
    { value: "Firebird_528", amount: 20 },
    { value: "Epiktetus", amount: 20 },
    { value: "IronMan9904", amount: 20 },
    { value: "Methos", amount: 20 },
    { value: "CrimsonAdder", amount: 20 },
    { value: "Emolga Sovietica", amount: 20 },
    { value: "ronninmc3", amount: 20 },
    { value: "Virexian", amount: 20 },
    { value: "Shattucknick", amount: 20 },
    { value: "GooseWaddle", amount: 20 },
    { value: "mojo blarp", amount: 20 },
    { value: "Abyzmi", amount: 20 },
    { value: "Cynnia", amount: 20 },
    { value: "Brynnium", amount: 20 },
    { value: "Ebonith", amount: 20 },
    { value: "Copper Wolf", amount: 20 },
    { value: "Kuretake41", amount: 20 },
    { value: "Jenmare", amount: 20 },
    { value: "DarkExcalibur42", amount: 20 },
    { value: "Crunch", amount: 20 },
    { value: "AeQuArTz", amount: 20 },
    { value: "Kenshipl", amount: 20 },
    { value: "Timotei~", amount: 20 },
    { value: "Ferraz", amount: 20 },
    { value: "Daemn", amount: 20 },
    { value: "JackSEC", amount: 20 },
    { value: "PitchBlack", amount: 20 },
    { value: "Lazer", amount: 20 },
    { value: "NightOwlModeler", amount: 20 },
    { value: "bobby vonsandwichface", amount: 20 },
    { value: "Cambox23", amount: 20 },
    { value: "CosmicAggressor", amount: 20 },
    { value: "Mert", amount: 20 },
    { value: "Th232", amount: 20 },
    { value: "Mister ПРОПЕР", amount: 20 },
    { value: "bastelork", amount: 20 },
    { value: "DanteVento", amount: 20 },
    { value: "wilhelmsfifthreich", amount: 20 },
    { value: "{Oblivious},Artsentin", amount: 20 },
    { value: "Sultor_Canerious", amount: 20 },
    { value: "Zerutzli♠ YYSF", amount: 19 },
    { value: "Sigma", amount: 19 },
    { value: "Kyan", amount: 19 },
    { value: "CDR Aurora", amount: 19 },
    { value: "Droid", amount: 19 },
    { value: "Smokki", amount: 19 },
    { value: "Water_Cat1", amount: 19 },
    { value: "arsenich12", amount: 19 },
    { value: "Renz", amount: 19 },
    { value: "sentimiento de rechazo de Jack", amount: 19 },
    { value: "VasFox_", amount: 19 },
    { value: "Webserfer22", amount: 19 },
    { value: "Ragtag", amount: 19 },
    { value: "Djelle", amount: 19 },
    { value: "Grockle", amount: 19 },
    { value: "DWD", amount: 19 },
    { value: "pineappleman", amount: 19 },
    { value: "Patoo", amount: 19 },
    { value: "4Steel", amount: 19 },
    { value: "jtfroh", amount: 19 },
    { value: "Texfire", amount: 19 },
    { value: "Mooka", amount: 19 },
    { value: "[PRH] Ibubr", amount: 19 },
    { value: "レイシア | Pitohui", amount: 19 },
    { value: "Joachim_Berger", amount: 19 },
    { value: "SpaceC", amount: 19 },
    { value: "Dr. Laurenz Geistert", amount: 19 },
    { value: "Avendril", amount: 19 },
    { value: "Sickno", amount: 19 },
    { value: "LV_Sweety", amount: 19 },
    { value: "The Toast of Cinder", amount: 19 },
    { value: "DrF3lix", amount: 19 },
    { value: "PursueR", amount: 19 },
    { value: "MasterUhu", amount: 19 },
    { value: "ＢяÎᴍρ |Desert Cat", amount: 19 },
    { value: "Salt Powered Robot", amount: 19 },
    { value: "polaris80red", amount: 19 },
    { value: "Huvi", amount: 19 },
    { value: "(V)AZDES (eng)", amount: 19 },
    { value: "shado3ofneo", amount: 19 },
    { value: "NWD84", amount: 19 },
    { value: "NIXIFOX_JP", amount: 19 },
    { value: "TheAlaskan", amount: 19 },
    { value: "mrdzarek", amount: 19 },
    { value: "SHOPlanB", amount: 19 },
    { value: "Kracker", amount: 19 },
    { value: "MrChleb-468_", amount: 19 },
    { value: "Walther_Weiß", amount: 19 },
    { value: "Titan In The Mist", amount: 19 },
    { value: "Khjin", amount: 19 },
    { value: "Kel_Thezuad", amount: 19 },
    { value: "(},-:<[ BlackRedDead ]>:-{)", amount: 19 },
    { value: "Hihiguy", amount: 19 },
    { value: "Zed", amount: 19 },
    { value: "thexypris", amount: 19 },
    { value: "Zevriun", amount: 19 },
    { value: "Rich", amount: 19 },
    { value: "KRAVCHENKO", amount: 19 },
    { value: "Joseppe G", amount: 19 },
    { value: "N1CK3R", amount: 19 },
    { value: "Zerberus", amount: 19 },
    { value: "QuikQuestion", amount: 19 },
    { value: "1251085184", amount: 19 },
    { value: "WashableChunk1", amount: 19 },
    { value: "Trebal", amount: 19 },
    { value: "Gman04", amount: 19 },
    { value: "Arrow of Time", amount: 19 },
    { value: "asun123com", amount: 19 },
    { value: "Aurumworks", amount: 19 },
    { value: "garaip97", amount: 19 },
    { value: "HyperThrone", amount: 19 },
    { value: "RAFNEC", amount: 19 },
    { value: "craftyscotsman4F", amount: 18 },
    { value: "LukemNukem", amount: 18 },
    { value: "pompom6x", amount: 18 },
    { value: "stedo", amount: 18 },
    { value: "Retro Frog", amount: 18 },
    { value: "Ozzy", amount: 18 },
    { value: "adriangraham1", amount: 18 },
    { value: "TygrysT", amount: 18 },
    { value: "enhaxed", amount: 18 },
    { value: "bluestriker", amount: 18 },
    { value: "kacpergh6", amount: 18 },
    { value: "Garlik", amount: 18 },
    { value: "Kenobi", amount: 18 },
    { value: "gumby", amount: 18 },
    { value: "Hohes_C4™", amount: 18 },
    { value: "Dr. Darcy", amount: 18 },
    { value: "Junerocks", amount: 18 },
    { value: "Deadpool", amount: 18 },
    { value: "Morpheus", amount: 18 },
    { value: "jmunzi", amount: 18 },
    { value: "nubeees", amount: 18 },
    { value: "Cruealix", amount: 18 },
    { value: "shaslaro", amount: 18 },
    { value: "Truman", amount: 18 },
    { value: "Viezenaar", amount: 18 },
    { value: "Daldriose", amount: 18 },
    { value: "BT-Volodya", amount: 18 },
    { value: "Dak Smith", amount: 18 },
    { value: "UnrealLiam", amount: 18 },
    { value: "Corporal 50 call", amount: 18 },
    { value: "Kanajashi", amount: 18 },
    { value: "Wtpbultman", amount: 18 },
    { value: "Knez", amount: 18 },
    { value: "Mito", amount: 18 },
    { value: "SyntheticPanda", amount: 18 },
    { value: "TheMessyGhost", amount: 18 },
    { value: "Spacy", amount: 18 },
    { value: "geekmonk", amount: 18 },
    { value: "WillPWR", amount: 18 },
    { value: "1Forge2RuleThemAll", amount: 18 },
    { value: "☢LilTraumatik☢", amount: 18 },
    { value: "Mad Laddicus", amount: 18 },
    { value: "Saltand1", amount: 18 },
    { value: "Tristavius", amount: 18 },
    { value: "Alpha", amount: 18 },
    { value: "Somethinglikemyfavourites", amount: 18 },
    { value: "- Kaisert -", amount: 18 },
    { value: "goofy1864", amount: 18 },
    { value: "Yeto", amount: 18 },
    { value: "farrell1701", amount: 18 },
    { value: "Merrick", amount: 18 },
    { value: "Felis Cactus", amount: 18 },
    { value: "captainbladej52", amount: 18 },
    { value: "Sky Tempest", amount: 18 },
    { value: "CaptBigBang", amount: 18 },
    { value: "SGT Sevyrs", amount: 18 },
    { value: "nico", amount: 18 },
    { value: "KMax Prime", amount: 18 },
    { value: "Tang", amount: 18 },
    { value: "Not CavnFox", amount: 18 },
    { value: "CedGames", amount: 18 },
    { value: "EziahrSiX", amount: 18 },
    { value: "GeNurixRRus", amount: 18 },
    { value: "AlloyCat", amount: 18 },
    { value: "Karmaterrorᵁᴷ", amount: 18 },
    { value: "Acaredia", amount: 18 },
    { value: "【JARO】►_◄  ☢", amount: 18 },
    { value: "dan", amount: 18 },
    { value: "Si", amount: 18 },
    { value: "Rocketdog79", amount: 18 },
    { value: "L4Redbaron", amount: 17 },
    { value: "Mr. Green", amount: 17 },
    { value: "Video28_allred", amount: 17 },
    { value: "Sneel1", amount: 17 },
    { value: "gergelypuskaval", amount: 17 },
    { value: "Insane Engineer", amount: 17 },
    { value: "Rough Frenet", amount: 17 },
    { value: "jarbrack", amount: 17 },
    { value: "Arrow", amount: 17 },
    { value: "Son o'Petrified", amount: 17 },
    { value: "xcal13", amount: 17 },
    { value: "SCjake", amount: 17 },
    { value: "Woodroft", amount: 17 },
    { value: "Foxtrot Unit", amount: 17 },
    { value: "Soda", amount: 17 },
    { value: "SE-KI", amount: 17 },
    { value: "Scar", amount: 17 },
    { value: "Grae", amount: 17 },
    { value: "LordZarmack", amount: 17 },
    { value: "jonkennedy74", amount: 17 },
    { value: "BLACKOUT_66", amount: 17 },
    { value: "Ironduke42", amount: 17 },
    { value: "MagnusEffect", amount: 17 },
    { value: "Toffyman *DEUS VULT*", amount: 17 },
    { value: "Parrotmarauder327", amount: 17 },
    { value: "Hollow Voices", amount: 17 },
    { value: "PeteyPetePeteth", amount: 17 },
    { value: "Blu", amount: 17 },
    { value: "K__H", amount: 17 },
    { value: "Atro", amount: 17 },
    { value: "Happy_cow", amount: 17 },
    { value: "Skinface", amount: 17 },
    { value: "TangentialThreat", amount: 17 },
    { value: "NineSevenFive", amount: 17 },
    { value: "Dr.8lack", amount: 17 },
    { value: "Tycho", amount: 17 },
    { value: "Micho Katana", amount: 17 },
    { value: "guima3882889", amount: 17 },
    { value: "Ignis", amount: 17 },
    { value: "DR.URLF", amount: 17 },
    { value: "4mGoverSquatters", amount: 17 },
    { value: "Bswell", amount: 17 },
    { value: "ClibStroker", amount: 17 },
    { value: "shiftyshadow", amount: 17 },
    { value: "Ironwatsas", amount: 17 },
    { value: "BeneBearded", amount: 17 },
    { value: "[OR.C]Nillemann", amount: 17 },
    { value: "Whoopity Longjohn", amount: 17 },
    { value: "DesignerShark44", amount: 17 },
    { value: "TheEnderStorm", amount: 17 },
    { value: "Space Engie", amount: 17 },
    { value: "LK", amount: 17 },
    { value: "Ric le Rouge", amount: 17 },
    { value: "<LFR> Rebel", amount: 17 },
    { value: "Cougarbait", amount: 17 },
    { value: "Wertyburger", amount: 17 },
    { value: "aerghabaegeck", amount: 17 },
    { value: "ebanina", amount: 17 },
    { value: "Cassius Faux", amount: 17 },
    { value: "biolante9", amount: 17 },
    { value: "BlackUmbrellas", amount: 17 },
    { value: "X-wraith", amount: 17 },
    { value: "Aitrops", amount: 17 },
    { value: "Namacil", amount: 17 },
    { value: "Nemo", amount: 17 },
    { value: "Demagogue", amount: 17 },
    { value: "StrixUralensis", amount: 17 },
    { value: "Seff", amount: 17 },
    { value: "CryNox0910", amount: 17 },
    { value: "///A M G", amount: 17 },
    { value: "Acheron Fox", amount: 17 },
    { value: "Swifties", amount: 17 },
    { value: "Hansen", amount: 17 },
    { value: "Sir McCannonarms", amount: 17 },
    { value: "Red Ace Fred", amount: 17 },
    { value: "krimwand", amount: 17 },
    { value: "_susikohmelo_", amount: 17 },
    { value: "SoliderDino17", amount: 17 },
    { value: "RICO-SYDog", amount: 17 },
    { value: "Samloopy", amount: 17 },
    { value: "DocRabbit", amount: 16 },
    { value: "HurricaneGirl", amount: 16 },
    { value: "proxy2501", amount: 16 },
    { value: "Macross-frontier", amount: 16 },
    { value: "Nhoj1000", amount: 16 },
    { value: "461353919", amount: 16 },
    { value: "rlb", amount: 16 },
    { value: "Wholy Youtube", amount: 16 },
    { value: "[D34DVI0L3NT]", amount: 16 },
    { value: "Korvus", amount: 16 },
    { value: "Eto Hige", amount: 16 },
    { value: "Achilles", amount: 16 },
    { value: "LT Commander Mattman", amount: 16 },
    { value: "Candarian", amount: 16 },
    { value: "[FouS]Itharia", amount: 16 },
    { value: "Contre Sens", amount: 16 },
    { value: "Arya Slark", amount: 16 },
    { value: "Thomas Shelby", amount: 16 },
    { value: "ShockTNC", amount: 16 },
    { value: "Darranis the Kingslayer", amount: 16 },
    { value: "Bert Berto", amount: 16 },
    { value: "Cheetah", amount: 16 },
    { value: "Kunu(The Ghost)", amount: 16 },
    { value: "AryxErin", amount: 16 },
    { value: "Grand Admiral Felix", amount: 16 },
    { value: "BrmP", amount: 16 },
    { value: "Rasmus", amount: 16 },
    { value: "Lordspaceship", amount: 16 },
    { value: "Wrathtide", amount: 16 },
    { value: "Mike Dude", amount: 16 },
    { value: "ColorMak3r", amount: 16 },
    { value: "LordGil", amount: 16 },
    { value: "Michaël", amount: 16 },
    { value: "Pegas519", amount: 16 },
    { value: "Foxen", amount: 16 },
    { value: "ellis4149", amount: 16 },
    { value: "Airborne Elmo", amount: 16 },
    { value: "DMOrigin", amount: 16 },
    { value: "Xocliw", amount: 16 },
    { value: "KPECT", amount: 16 },
    { value: "LuMian300", amount: 16 },
    { value: "Doozer", amount: 16 },
    { value: "Serg", amount: 16 },
    { value: "=FrankUnit=", amount: 16 },
    { value: "balisticspace", amount: 16 },
    { value: "Carlos", amount: 16 },
    { value: "STARSAR", amount: 16 },
    { value: "MegaloDangerous", amount: 16 },
    { value: "UltimateCarnivore", amount: 16 },
    { value: "Atterus", amount: 16 },
    { value: "SpaceJace5428", amount: 16 },
    { value: "_Hedge_", amount: 16 },
    { value: "Rikc34", amount: 16 },
    { value: "Sich", amount: 16 },
    { value: "ZEO CMF", amount: 16 },
    { value: "Dec Plays", amount: 16 },
    { value: "Bobisback", amount: 16 },
    { value: "iZG|IridiuLugia", amount: 16 },
    { value: "Jeck", amount: 16 },
    { value: "Bullslayer", amount: 16 },
    { value: "Erling", amount: 16 },
    { value: "Giacomo_Panizza", amount: 16 },
    { value: "daizin3200", amount: 16 },
    { value: "FunkyMonkey", amount: 16 },
    { value: "_Alex_[cadet]_", amount: 16 },
    { value: "jegan1", amount: 16 },
    { value: "Mrbungle", amount: 16 },
    { value: "Projekt Pleasure", amount: 16 },
    { value: "TheSaltySeaMan.", amount: 16 },
    { value: "zjklp", amount: 16 },
    { value: "The PinkFair", amount: 16 },
    { value: "ROB", amount: 16 },
    { value: "uglydisease", amount: 16 },
    { value: "Konrak", amount: 16 },
    { value: "CipherZR032", amount: 16 },
    { value: "drowy", amount: 16 },
    { value: "DAX", amount: 16 },
    { value: "Telat Abiler", amount: 16 },
    { value: "一夜回到解放前", amount: 16 },
    { value: "dfirerush", amount: 15 },
    { value: "Vega", amount: 15 },
    { value: "Cup of  joe", amount: 15 },
    { value: "IFOOL", amount: 15 },
    { value: "Alphahex", amount: 15 },
    { value: "kot_kysaka", amount: 15 },
    { value: "INKY /ᐠ_ ꞈ _ᐟ\\", amount: 15 },
    { value: "ARC17Alpha", amount: 15 },
    { value: "clonk2u", amount: 15 },
    { value: "MrDataWolf", amount: 15 },
    { value: "Deviator", amount: 15 },
    { value: "BigShogun", amount: 15 },
    { value: "Tacet", amount: 15 },
    { value: "Puccilillo", amount: 15 },
    { value: "EnIgMaTiCoRaNgE", amount: 15 },
    { value: "Candle in the wind", amount: 15 },
    { value: "pizdec.exe", amount: 15 },
    { value: "Surtur", amount: 15 },
    { value: "DarrenPD95", amount: 15 },
    { value: "SKYLINE", amount: 15 },
    { value: "EgorKaskader", amount: 15 },
    { value: "johnny33445566", amount: 15 },
    { value: "Indigo 9Tails", amount: 15 },
    { value: "Leto", amount: 15 },
    { value: "DerekTheGreat", amount: 15 },
    { value: "Corock15th", amount: 15 },
    { value: "二营长", amount: 15 },
    { value: "Ekuah", amount: 15 },
    { value: "Warlocc", amount: 15 },
    { value: "Perksimis (Medic)", amount: 15 },
    { value: "VIK1NGTACT", amount: 15 },
    { value: "Your Pal Deebs", amount: 15 },
    { value: "Le Funny Round Fishe", amount: 15 },
    { value: "SlimSumo", amount: 15 },
    { value: "Shadestuff", amount: 15 },
    { value: "joefreeman666", amount: 15 },
    { value: "Nyx", amount: 15 },
    { value: "Morilibus", amount: 15 },
    { value: "Creative", amount: 15 },
    { value: "Optimistically pessimistic", amount: 15 },
    { value: "Onyx", amount: 15 },
    { value: "plaYer2k", amount: 15 },
    { value: "Popeychops", amount: 15 },
    { value: "Jax", amount: 15 },
    { value: "🅷er🆆on🆉iemniak", amount: 15 },
    { value: "Vaalyion", amount: 15 },
    { value: "SkyCrafterLeague", amount: 15 },
    { value: "matt_daponte", amount: 15 },
    { value: "KnightShade", amount: 15 },
    { value: "Jolly", amount: 15 },
    { value: "thebeautyofwars", amount: 15 },
    { value: "Tsubasa", amount: 15 },
    { value: "DC-David", amount: 15 },
    { value: "Z'Kell Taldor", amount: 15 },
    { value: "Sundae", amount: 15 },
    { value: "𝔻𝔼ℕ𝕁𝔼𝕃", amount: 15 },
    { value: "S_For_Sonic1235", amount: 15 },
    { value: "Jakaria", amount: 15 },
    { value: "The MiningMan", amount: 15 },
    { value: "UnagiKing", amount: 15 },
    { value: "Tyrael", amount: 15 },
    { value: "Nathan.Bean", amount: 15 },
    { value: "Bio Blaster", amount: 15 },
    { value: "Ravric", amount: 15 },
    { value: "CATMAN", amount: 15 },
    { value: "Souzen Yurama", amount: 15 },
    { value: "roisinge77", amount: 15 },
    { value: "shamw0w", amount: 15 },
    { value: "Elementary", amount: 15 },
    { value: "JulianGamezZz", amount: 15 },
    { value: "BCP Labs(YT)", amount: 15 },
    { value: "dgwgamer", amount: 15 },
    { value: "rommelfcc", amount: 15 },
    { value: "zooxanthellaeh2o", amount: 15 },
    { value: "Lady FaiiDarra", amount: 15 },
    { value: "No", amount: 15 },
    { value: "Hawk Eye", amount: 15 },
    { value: "NebuLord", amount: 15 },
    { value: "robossbomb", amount: 15 },
    { value: "JordanRiver", amount: 15 },
    { value: "ominusthreat", amount: 15 },
    { value: "jayteeree", amount: 15 },
    { value: "Necrosexual", amount: 15 },
    { value: "JakeL", amount: 15 },
    { value: "WannabeWallaby", amount: 15 },
    { value: "Jman_jd10", amount: 15 },
    { value: "ANOREXIC_DWARF", amount: 15 },
    { value: "bobamorgan", amount: 15 },
    { value: "Mach-330", amount: 15 },
    { value: "-=TheDecisiveRaindrop=-", amount: 15 },
    { value: "Alexander", amount: 15 },
    { value: "JesusThatsMe", amount: 15 },
    { value: "SlOtHy", amount: 15 },
    { value: "NeroDrake", amount: 15 },
    { value: "HEATHEN", amount: 15 },
    { value: "Phil", amount: 15 },
    { value: "BrainProtest", amount: 15 },
    { value: "The_AzureDragon", amount: 15 },
    { value: "posthy", amount: 15 },
    { value: "Rct. Kahrstrom [193rd GIR]", amount: 15 },
    { value: "sith233", amount: 15 },
    { value: "--{ Herald of Death },--", amount: 15 },
    { value: "AnoMorgan", amount: 15 },
    { value: "mistertreky2007", amount: 15 },
    { value: "Gelda", amount: 14 },
    { value: "Centauri", amount: 14 },
    { value: "TwinChops", amount: 14 },
    { value: "JANO", amount: 14 },
    { value: "ace_334", amount: 14 },
    { value: "levink64", amount: 14 },
    { value: "Alb", amount: 14 },
    { value: "Chefchik", amount: 14 },
    { value: "Hi.itsJonny", amount: 14 },
    { value: "Audacious Duke", amount: 14 },
    { value: "Scrubus", amount: 14 },
    { value: "shadowpheonix787", amount: 14 },
    { value: "Atomsk", amount: 14 },
    { value: "Vyron [UA]", amount: 14 },
    { value: "LandoBiggins", amount: 14 },
    { value: "TheOneTNT", amount: 14 },
    { value: "dgeodgeo", amount: 14 },
    { value: "Slacker82", amount: 14 },
    { value: "Nicgamer07", amount: 14 },
    { value: "RosE", amount: 14 },
    { value: "[ LeoVircen ]", amount: 14 },
    { value: "NYET RIFLE IS FINE!", amount: 14 },
    { value: "Raon Lee", amount: 14 },
    { value: "Dr. Mike", amount: 14 },
    { value: "Ratio Tile", amount: 14 },
    { value: "andi", amount: 14 },
    { value: "Tyrenol", amount: 14 },
    { value: "ManicMonster44", amount: 14 },
    { value: "Nergal", amount: 14 },
    { value: "water lily", amount: 14 },
    { value: "jonnytaco", amount: 14 },
    { value: "DarthVaper", amount: 14 },
    { value: "Jamsey", amount: 14 },
    { value: "bruce.dubois6", amount: 14 },
    { value: "amigo-robin", amount: 14 },
    { value: "Arkideit", amount: 14 },
    { value: "Fissiondivision", amount: 14 },
    { value: "Bovidius", amount: 14 },
    { value: "Tanis", amount: 14 },
    { value: "Jack Faltrow", amount: 14 },
    { value: "CTH2004", amount: 14 },
    { value: "Doctor Octoganapus", amount: 14 },
    { value: "1llusionist", amount: 14 },
    { value: "Whitefox3030", amount: 14 },
    { value: "woostyboy", amount: 14 },
    { value: "SumY", amount: 14 },
    { value: "Thor", amount: 14 },
    { value: "Alyshan", amount: 14 },
    { value: "Sir Luis", amount: 14 },
    { value: "BIGOLBEAR", amount: 14 },
    { value: "SugarFett", amount: 14 },
    { value: "᠌ ᠌", amount: 14 },
    { value: "System_32", amount: 14 },
    { value: "Lazlo", amount: 14 },
    { value: "Dachshund", amount: 14 },
    { value: "Korgann", amount: 14 },
    { value: "TristanDolfin", amount: 14 },
    { value: "autocyb227", amount: 14 },
    { value: "Mrphoen1x", amount: 14 },
    { value: "Grindy Gears", amount: 14 },
    { value: "S1meX", amount: 14 },
    { value: "B.Wookie", amount: 14 },
    { value: "TheLastDefence", amount: 14 },
    { value: "SMEGG12", amount: 14 },
    { value: "Vigik the broken", amount: 14 },
    { value: "BanRuh", amount: 14 },
    { value: "LordTylus", amount: 14 },
    { value: "Elite tempest", amount: 14 },
    { value: "BKFighter", amount: 14 },
    { value: "firsimp", amount: 14 },
    { value: "battery1979", amount: 14 },
    { value: "Rufio", amount: 14 },
    { value: "Action Hank", amount: 14 },
    { value: "BuzZz Killer", amount: 14 },
    { value: "redspirit69", amount: 14 },
    { value: "Tuuvas", amount: 14 },
    { value: "Vermilion", amount: 14 },
    { value: "MechGingineer", amount: 14 },
    { value: "Azazel", amount: 14 },
    { value: "keiththefish", amount: 14 },
    { value: "一只腹黑的猫", amount: 14 },
    { value: "Shimaletik", amount: 14 },
    { value: "TheMightyPilot", amount: 14 },
    { value: "Shadow", amount: 14 },
    { value: "Atlas", amount: 14 },
    { value: "SkywardSoul117", amount: 14 },
    { value: "UMB694", amount: 14 },
    { value: "ManInTheFoilMask", amount: 14 },
    { value: "Solrob's Tetrohedron", amount: 14 },
    { value: "Bison", amount: 14 },
    { value: "HUBERT THE ROCK", amount: 14 },
    { value: "Cirshiss", amount: 14 },
    { value: "SteelX", amount: 14 },
    { value: "DriftedCougar84", amount: 14 },
    { value: "Hunter", amount: 14 },
    { value: "Oxygentleman", amount: 14 },
    { value: "gar_krol", amount: 14 },
    { value: "Abuu", amount: 14 },
    { value: "Vandaan", amount: 14 },
    { value: "Merrickxx Gaming", amount: 14 },
    { value: "Ahab", amount: 14 },
    { value: "Ariffet_Orlase013", amount: 14 },
    { value: "MagnaGazoo", amount: 14 },
    { value: "[AI]666Savior", amount: 14 },
    { value: "SkyeTea", amount: 14 },
    { value: "lord_vigo", amount: 14 },
    { value: "Clockwork Gobber", amount: 14 },
    { value: "Alos", amount: 14 },
    { value: "SeliG", amount: 14 },
    { value: "Lahne_HD", amount: 14 },
    { value: "Arbalest", amount: 14 },
    { value: "Fagotto", amount: 14 },
    { value: "ImaDirtyBirdy", amount: 14 },
    { value: "Bdeslaurs", amount: 14 },
    { value: "Elbliep0", amount: 14 },
    { value: "M4Wi", amount: 14 },
    { value: "Горячий Павел", amount: 14 },
    { value: "LurLemur", amount: 14 },
    { value: "Konigerino", amount: 14 },
    { value: "djfigs25", amount: 14 },
    { value: "Dankirish", amount: 14 },
    { value: "SavenSat YT", amount: 14 },
    { value: "King Arthur", amount: 14 },
    { value: "Snake Eyes", amount: 13 },
    { value: "xxk0y0t3xx", amount: 13 },
    { value: "Kонтроль", amount: 13 },
    { value: "karas", amount: 13 },
    { value: "stelladraco27", amount: 13 },
    { value: "[102nd] TheEmperor", amount: 13 },
    { value: "stretchtwo587", amount: 13 },
    { value: "Holy Crusader", amount: 13 },
    { value: "Recurve", amount: 13 },
    { value: "DreamAssembly!", amount: 13 },
    { value: "s0ver", amount: 13 },
    { value: "Zero", amount: 13 },
    { value: "RKS-GameTech", amount: 13 },
    { value: "seawolf", amount: 13 },
    { value: "Br-35 Ba-56", amount: 13 },
    { value: "bruin_o9er", amount: 13 },
    { value: "Seza", amount: 13 },
    { value: "ZZZhua", amount: 13 },
    { value: "FasterHaJo", amount: 13 },
    { value: "Rowan", amount: 13 },
    { value: "jmferretmaster", amount: 13 },
    { value: "Downey", amount: 13 },
    { value: "Lord|Monkey", amount: 13 },
    { value: "Lith83", amount: 13 },
    { value: "BOB ROSS THE SAUCE BOSS", amount: 13 },
    { value: "Lead Pill", amount: 13 },
    { value: "Hujambo-2", amount: 13 },
    { value: "Blackvertigo1", amount: 13 },
    { value: "stuckyluke", amount: 13 },
    { value: "SOBERANO", amount: 13 },
    { value: "SheriffYuri", amount: 13 },
    { value: "WarBeast", amount: 13 },
    { value: "Synergy", amount: 13 },
    { value: "Neocade", amount: 13 },
    { value: "El Orco De Denetorko", amount: 13 },
    { value: "Anzaic", amount: 13 },
    { value: "Buttered Toast", amount: 13 },
    { value: "Koven", amount: 13 },
    { value: "Nomida  (Sim)", amount: 13 },
    { value: "Rowller", amount: 13 },
    { value: "AssHunter", amount: 13 },
    { value: "Unreal", amount: 13 },
    { value: "Kronk", amount: 13 },
    { value: "Spacepotato9000", amount: 13 },
    { value: "IraGfC", amount: 13 },
    { value: "Azure Night Owl", amount: 13 },
    { value: "DragonTemplar4", amount: 13 },
    { value: "T Man 123201", amount: 13 },
    { value: "Aeyos", amount: 13 },
    { value: "Huwinator", amount: 13 },
    { value: "Quantum Joe", amount: 13 },
    { value: "FOE*HAMMER", amount: 13 },
    { value: "Leroy", amount: 13 },
    { value: "Nomad", amount: 13 },
    { value: "Gatin' Jin", amount: 13 },
    { value: "creothes", amount: 13 },
    { value: "ckobler", amount: 13 },
    { value: "Minecraft Kosticka", amount: 13 },
    { value: "darkheyr", amount: 13 },
    { value: "Liberty Bull", amount: 13 },
    { value: "Riddell", amount: 13 },
    { value: "Paarl7", amount: 13 },
    { value: "Cuica", amount: 13 },
    { value: "warlord-inc", amount: 13 },
    { value: "Conscripted Alchemist", amount: 13 },
    { value: "lolindirarfar", amount: 13 },
    { value: "anton.bikovsky", amount: 13 },
    { value: "Pen'nar Empire", amount: 13 },
    { value: "F4TALG4MER", amount: 13 },
    { value: "['0] Handsome Jack", amount: 13 },
    { value: "Pills&Pie™", amount: 13 },
    { value: "Jexsam", amount: 13 },
    { value: "Game Time", amount: 13 },
    { value: "Callidis", amount: 13 },
    { value: "Mr Nobody", amount: 13 },
    { value: "Captain_REX", amount: 13 },
    { value: "Rage insanity", amount: 13 },
    { value: "Xylophone", amount: 13 },
    { value: "RoutineTree3", amount: 13 },
    { value: "Felavendel", amount: 13 },
    { value: "Flashblaster", amount: 13 },
    { value: "Auska", amount: 13 },
    { value: "komodau", amount: 13 },
    { value: "Mr. Blobby", amount: 13 },
    { value: "Ender", amount: 13 },
    { value: "Wemi", amount: 13 },
    { value: "Lightning Lord", amount: 13 },
    { value: "editedcub", amount: 13 },
    { value: "NinjaBreadroll", amount: 13 },
    { value: "BestMikeEver", amount: 13 },
    { value: "Xephrock", amount: 13 },
    { value: "Takaifa", amount: 13 },
    { value: "Sck Superman", amount: 13 },
    { value: "Wicorel", amount: 13 },
    { value: "Rawr", amount: 13 },
    { value: "Gef509", amount: 13 },
    { value: "CMDR Nyxton", amount: 13 },
    { value: "Badger✈", amount: 13 },
    { value: "rockrove", amount: 13 },
    { value: "Callsign \'Ghost Rider\'", amount: 13 },
    { value: "Ulrich_Von_Jungingen", amount: 13 },
    { value: "costellokalani", amount: 13 },
    { value: "☭Android☭", amount: 13 },
    { value: "Harley Quinn", amount: 13 },
    { value: "JDprimus_2199 FR", amount: 13 },
    { value: "denismaster", amount: 13 },
    { value: "DurFea", amount: 13 },
    { value: "Space Man", amount: 13 },
    { value: "NAMZYHD4", amount: 13 },
    { value: "Alexli14", amount: 13 },
    { value: "Bengemon825", amount: 13 },
    { value: "pro100tv", amount: 13 },
    { value: "Fenrisulfr", amount: 13 },
    { value: "SpaceRak", amount: 13 },
    { value: "ÆGIS", amount: 13 },
    { value: "Egliru The Best Mate of Okonkwo", amount: 13 },
    { value: "Retro97Assault", amount: 13 },
    { value: "[D3RP] Meserion", amount: 13 },
    { value: "SkyCaptainSleepy", amount: 13 },
    { value: "Terminal_6", amount: 13 },
    { value: "GinderMan", amount: 13 },
    { value: "Brent", amount: 13 },
    { value: "dust bowl farmer", amount: 13 },
    { value: "JustARaceThing", amount: 13 },
    { value: "Roy2D2C", amount: 13 },
    { value: "Glutbart", amount: 13 },
    { value: "skivel2", amount: 13 },
    { value: "armored_saint", amount: 13 },
    { value: "Papi62", amount: 13 },
    { value: "Space Marine", amount: 13 },
    { value: "Mannorot2015", amount: 13 },
    { value: "UMAN", amount: 13 },
    { value: "Temporary Banana", amount: 13 },
    { value: "SpaceKeek", amount: 13 },
    { value: "cofish11", amount: 13 },
    { value: "UltraYT", amount: 13 },
    { value: "ranus_magnus", amount: 13 },
    { value: "Neravian", amount: 13 },
    { value: "Chad", amount: 13 },
    { value: "ZenWalker", amount: 13 },
    { value: "f2nt4sm6", amount: 13 },
    { value: "Copycat80", amount: 13 },
    { value: "王天", amount: 12 },
    { value: "Azurite", amount: 12 },
    { value: "nickglaza", amount: 12 },
    { value: "Scarlet Vanhansson", amount: 12 },
    { value: "MadThanos [EST] ™", amount: 12 },
    { value: "RogenLothena™", amount: 12 },
    { value: "SGT Wise", amount: 12 },
    { value: "nemo187", amount: 12 },
    { value: "reload", amount: 12 },
    { value: "Joe", amount: 12 },
    { value: "PATS3Y", amount: 12 },
    { value: "Tommy Lee", amount: 12 },
    { value: "Rolins-Carter", amount: 12 },
    { value: "Gray", amount: 12 },
    { value: "SquishyBunz23", amount: 12 },
    { value: "pawelsake", amount: 12 },
    { value: "JOSELUIS(SDT)", amount: 12 },
    { value: "Commander Joir", amount: 12 },
    { value: "The_Prince_Of_Fails", amount: 12 },
    { value: "FakeFox", amount: 12 },
    { value: "[SPITFYRE] kjs", amount: 12 },
    { value: "Kashiwa", amount: 12 },
    { value: "rawstyler", amount: 12 },
    { value: "SurF HKAZ", amount: 12 },
    { value: "358205434", amount: 12 },
    { value: "SolidRockGaming", amount: 12 },
    { value: "hcor88", amount: 12 },
    { value: "Mr Creative", amount: 12 },
    { value: "Ostpol", amount: 12 },
    { value: "ragnarcore", amount: 12 },
    { value: "Mr. Steel", amount: 12 },
    { value: "shadow trace", amount: 12 },
    { value: "jemtzgr", amount: 12 },
    { value: "Midas", amount: 12 },
    { value: "WarDragon", amount: 12 },
    { value: "Sniforge", amount: 12 },
    { value: "anzellott", amount: 12 },
    { value: "Loues.S.Cat", amount: 12 },
    { value: "PsychoticSpud", amount: 12 },
    { value: "Lassie", amount: 12 },
    { value: "Sharbert Warbison", amount: 12 },
    { value: "TIM", amount: 12 },
    { value: "TheSpawnyGit", amount: 12 },
    { value: "紫阳", amount: 12 },
    { value: "jarge2", amount: 12 },
    { value: "Glados_Hamster", amount: 12 },
    { value: "ARK", amount: 12 },
    { value: "FlutterPoneShy", amount: 12 },
    { value: "biker.bandit", amount: 12 },
    { value: "Shagakor", amount: 12 },
    { value: "Matya", amount: 12 },
    { value: "fps_Al'Mexinugget", amount: 12 },
    { value: "kokimimi", amount: 12 },
    { value: "Raptor", amount: 12 },
    { value: "El Pako III", amount: 12 },
    { value: "TwitchENs [DSN]", amount: 12 },
    { value: "Dalek_Sath", amount: 12 },
    { value: "Psycho", amount: 12 },
    { value: "Entersprite", amount: 12 },
    { value: "[NSE]Blaster", amount: 12 },
    { value: "revox79", amount: 12 },
    { value: "McGargoyle", amount: 12 },
    { value: "DERPY SMOOG", amount: 12 },
    { value: "Abaj13", amount: 12 },
    { value: "Sky", amount: 12 },
    { value: "HAKATJI", amount: 12 },
    { value: "Boldtaar", amount: 12 },
    { value: "HrvyWllbngr", amount: 12 },
    { value: "Zer0 Dark", amount: 12 },
    { value: "Ace ", amount: 12 },
    { value: "Rikku", amount: 12 },
    { value: "Gyrexion", amount: 12 },
    { value: "Shyska Ronja", amount: 12 },
    { value: "Wari0R", amount: 12 },
    { value: "MagnumOpus", amount: 12 },
    { value: "danghul", amount: 12 },
    { value: "cybersettler", amount: 12 },
    { value: "Turkeybaster", amount: 12 },
    { value: "SkullmanAlpha", amount: 12 },
    { value: "Gekreth", amount: 12 },
    { value: "Onikage-056, God of Animatronics", amount: 12 },
    { value: "张碎蛋同学", amount: 12 },
    { value: "[SRT] Admiral Skyron", amount: 12 },
    { value: "randeep74.singh", amount: 12 },
    { value: "juststephen", amount: 12 },
    { value: "DirectedEnergy", amount: 12 },
    { value: "Dradin", amount: 12 },
    { value: "[FFC] Maxx", amount: 12 },
    { value: "Loki", amount: 12 },
    { value: "Mittons", amount: 12 },
    { value: "pierreextraperry", amount: 12 },
    { value: "Cpt.P.Chvatal", amount: 12 },
    { value: "AppexDragon", amount: 12 },
    { value: "SiriusBlack", amount: 12 },
    { value: "DeC", amount: 12 },
    { value: "MRfihka", amount: 12 },
    { value: "JDM", amount: 12 },
    { value: "Isen", amount: 12 },
    { value: "FullMoonJoker", amount: 12 },
    { value: "jack.burke98", amount: 12 },
    { value: "Voxnic", amount: 12 },
    { value: "chillinflute", amount: 12 },
    { value: "mmaaddnndd12", amount: 12 },
    { value: "The Shippo T⍑ᒷ s⍑╎!¡!¡𝙹", amount: 12 },
    { value: "Fulcrum", amount: 12 },
    { value: "Xsniper9898", amount: 12 },
    { value: "Wild Wild Wez", amount: 12 },
    { value: "S1m0n3", amount: 12 },
    { value: "Sgt_YorkA63", amount: 12 },
    { value: "eisenhammertech", amount: 12 },
    { value: "jerryfanfan", amount: 12 },
    { value: "SirTragain", amount: 12 },
    { value: "Irkalla", amount: 12 },
    { value: "Kyr", amount: 12 },
    { value: "No Signal", amount: 12 },
    { value: "Tekk", amount: 12 },
    { value: "Jaggster (Dimension C-132)", amount: 12 },
    { value: "victor.e.mondragon@gmail.com", amount: 12 },
    { value: "Misnn", amount: 12 },
    { value: "SoldierHN03", amount: 12 },
    { value: "GOOENSKEW", amount: 12 },
    { value: "SubZero", amount: 12 },
    { value: "Chicken_Duck_Foot_Thing", amount: 12 },
    { value: "Raeffi", amount: 12 },
    { value: "Soulebot", amount: 12 },
    { value: "Deja Vroom!", amount: 12 },
    { value: "Lugubrious Orifice", amount: 12 },
    { value: "cszlak", amount: 12 },
    { value: "CruelBacon", amount: 12 },
    { value: "Gimboid", amount: 12 },
    { value: "JoshyBOB", amount: 12 },
    { value: "Neon Photon", amount: 12 },
    { value: "Cubbage", amount: 12 },
    { value: "Evangelion139", amount: 12 },
    { value: "ZippedTrojan", amount: 12 },
    { value: "Spook-27", amount: 12 },
    { value: "Grimard", amount: 12 },
    { value: "Thentox", amount: 12 },
    { value: "E-Man720", amount: 12 },
    { value: "EpicElric", amount: 12 },
    { value: "Noorthia", amount: 12 },
    { value: "Maybach", amount: 12 },
    { value: "LordAlexkog", amount: 12 },
    { value: "Dax Nexus", amount: 12 },
    { value: "Digi", amount: 12 },
    { value: "Commander_JCM", amount: 12 },
    { value: "Marcus 🔰", amount: 12 },
    { value: "Sebforce116", amount: 12 },
    { value: "IamTheHavoc", amount: 12 },
    { value: "zipgunlarry", amount: 12 },
    { value: "Richard", amount: 12 },
    { value: "RedFly", amount: 12 },
    { value: "IronOxide", amount: 12 },
    { value: "Spawn-of-Dark", amount: 12 },
    { value: "OguzHAN ONBIR", amount: 12 },
    { value: "The Wolf", amount: 12 },
    { value: "juusukun", amount: 12 },
    { value: "Tumble", amount: 12 },
    { value: "Sekston Turretmaster", amount: 12 },
    { value: "Terradus", amount: 12 },
    { value: "Malhavoc", amount: 12 },
    { value: "Gunnar", amount: 12 },
    { value: "TuntematonSika", amount: 12 },
    { value: "Zefnoly", amount: 12 },
    { value: "71№B1", amount: 11 },
    { value: "Rv2pc3d", amount: 11 },
    { value: "Riley Reid", amount: 11 },
    { value: "jtreiman", amount: 11 },
    { value: "Sarah", amount: 11 },
    { value: "shamsi", amount: 11 },
    { value: "Exo Vanders", amount: 11 },
    { value: "anime212001", amount: 11 },
    { value: "Kuro6", amount: 11 },
    { value: "Stay Cool", amount: 11 },
    { value: "ThatOneDisco", amount: 11 },
    { value: "LordBUM", amount: 11 },
    { value: "Shepard (KeGGeR)", amount: 11 },
    { value: "WickeD", amount: 11 },
    { value: "hubbletowne", amount: 11 },
    { value: "Amp-Hibious", amount: 11 },
    { value: "WallofBriggs", amount: 11 },
    { value: "Deukmans", amount: 11 },
    { value: "LuckingY·Bitle六百萬🌟", amount: 11 },
    { value: "Captain J. Wolf", amount: 11 },
    { value: "ZAULON5⓪5Relax", amount: 11 },
    { value: "Holyschytt", amount: 11 },
    { value: "Marc Cassin", amount: 11 },
    { value: "TEEN", amount: 11 },
    { value: "scramps", amount: 11 },
    { value: "Slagger", amount: 11 },
    { value: "bc007", amount: 11 },
    { value: "B.A_54", amount: 11 },
    { value: "Clipboard", amount: 11 },
    { value: "Marre91", amount: 11 },
    { value: "Trojan", amount: 11 },
    { value: "Gentle George", amount: 11 },
    { value: "PainfulCh33se", amount: 11 },
    { value: "Marshall", amount: 11 },
    { value: "cmagnoramalho", amount: 11 },
    { value: "LittleManWilliam", amount: 11 },
    { value: "Karnivool", amount: 11 },
    { value: "aishen27", amount: 11 },
    { value: "BCORNO", amount: 11 },
    { value: "Gravediger", amount: 11 },
    { value: "HDLiggett", amount: 11 },
    { value: "BigSmoke.", amount: 11 },
    { value: "mipam", amount: 11 },
    { value: "Darp", amount: 11 },
    { value: "LHammonds", amount: 11 },
    { value: "Hitman (GER)", amount: 11 },
    { value: "Gufo10", amount: 11 },
    { value: "Gridinad", amount: 11 },
    { value: "DeathMagnet", amount: 11 },
    { value: "MFDreamless", amount: 11 },
    { value: "WelshTurtle", amount: 11 },
    { value: "Takeshi", amount: 11 },
    { value: "carlosewilfong", amount: 11 },
    { value: "The God of LP", amount: 11 },
    { value: "coyote", amount: 11 },
    { value: "Carbondatez", amount: 11 },
    { value: "IRONNOX", amount: 11 },
    { value: "Obi-vanvan7", amount: 11 },
    { value: "plopyorange8100", amount: 11 },
    { value: "Roboneer99", amount: 11 },
    { value: "Errix", amount: 11 },
    { value: "rjavier441", amount: 11 },
    { value: "mr morsquito", amount: 11 },
    { value: "Dravidian", amount: 11 },
    { value: "Hacker3k", amount: 11 },
    { value: "andreyas.1982", amount: 11 },
    { value: "grimczz", amount: 11 },
    { value: "MONO", amount: 11 },
    { value: "Professor Holtex [GER]", amount: 11 },
    { value: "CrossXx", amount: 11 },
    { value: "ShardExtra", amount: 11 },
    { value: "KT_pg_Fordring", amount: 11 },
    { value: "ElectronDev", amount: 11 },
    { value: "jabtiger0322reborn", amount: 11 },
    { value: "APOLLONFX", amount: 11 },
    { value: "jumpingdoghead", amount: 11 },
    { value: "Starsunder", amount: 11 },
    { value: "FoxVelox", amount: 11 },
    { value: "body1986", amount: 11 },
    { value: "Zintlede", amount: 11 },
    { value: "laci4321 (HUN)", amount: 11 },
    { value: "SuspiciousCheese", amount: 11 },
    { value: "Celtix", amount: 11 },
    { value: "Still Unnamed", amount: 11 },
    { value: "Storm", amount: 11 },
    { value: "Tuttomenui", amount: 11 },
    { value: "Unknown Playe72", amount: 11 },
    { value: "Uncertain DOOM", amount: 11 },
    { value: "Paomf", amount: 11 },
    { value: "SkilledX", amount: 11 },
    { value: "ravadja", amount: 11 },
    { value: "Anoth", amount: 11 },
    { value: "ShadowSabre1", amount: 11 },
    { value: "steve8888888816", amount: 11 },
    { value: "yacabo", amount: 11 },
    { value: "Jay-ar | Tradeit.gg", amount: 11 },
    { value: "ж  ﻿ｔｅｒｚａｅｒｉａｎ  ✌", amount: 11 },
    { value: "Vreenak", amount: 11 },
    { value: "sacul2345", amount: 11 },
    { value: "Infantry56", amount: 11 },
    { value: "sabertooth512", amount: 11 },
    { value: "The_Epic_Beard", amount: 11 },
    { value: "☢ SHIT SPLASH ☢", amount: 11 },
    { value: "CAPTAIN SIRSOG", amount: 11 },
    { value: "Steven", amount: 11 },
    { value: "The Mjrlun", amount: 11 },
    { value: "Ayotrex", amount: 11 },
    { value: "tesunie", amount: 11 },
    { value: "Aramagon_ZA", amount: 11 },
    { value: "Bvol", amount: 11 },
    { value: "epflederer", amount: 11 },
    { value: "Baleur", amount: 11 },
    { value: "Trekker", amount: 11 },
    { value: "Crimson Revenant", amount: 11 },
    { value: "roadieshow", amount: 11 },
    { value: "FlabMush", amount: 11 },
    { value: "Abstract_Enigma", amount: 11 },
    { value: "TheGreebleAdict", amount: 11 },
    { value: "ArcBlue", amount: 11 },
    { value: "Kira", amount: 11 },
    { value: "Specter02", amount: 11 },
    { value: "JEWDAY", amount: 11 },
    { value: "FireGuy1996", amount: 11 },
    { value: "Seromas", amount: 11 },
    { value: "Daroneyn", amount: 11 },
    { value: "Baratheon79", amount: 11 },
    { value: "marcelkas83", amount: 11 },
    { value: "999", amount: 11 },
    { value: "yggdra222", amount: 11 },
    { value: "Legion40k", amount: 11 },
    { value: "Night.Watchman", amount: 11 },
    { value: "roman.bezsmertniy", amount: 11 },
    { value: "Dextroghost", amount: 11 },
    { value: "Dr Crow", amount: 11 },
    { value: "jojaca3", amount: 11 },
    { value: "Morfin", amount: 11 },
    { value: "Dr. Amethyst Spell", amount: 11 },
    { value: "Candor", amount: 11 },
    { value: "termen8or", amount: 11 },
    { value: "1eyewilly", amount: 11 },
    { value: "DanTheDutchMan", amount: 11 },
    { value: "KlausVonBlunderSchmuck", amount: 11 },
    { value: "Nadia Gottlieb", amount: 11 },
    { value: "Mr Hazard", amount: 11 },
    { value: "Aydo", amount: 11 },
    { value: "blackmancer", amount: 11 },
    { value: "Robka", amount: 11 },
    { value: "Brave", amount: 11 },
    { value: "Willy Gmod", amount: 11 },
    { value: "Wackyboy", amount: 11 },
    { value: "Torchwood", amount: 11 },
    { value: "QcGrumble", amount: 11 },
    { value: "Coopster", amount: 11 },
    { value: "Ligon", amount: 11 },
    { value: "Rayleonardo", amount: 11 },
    { value: "Starbuckminsterfullerton", amount: 11 },
    { value: "kick_butz", amount: 11 },
    { value: "J. Ryan", amount: 11 },
    { value: "Spaghetti Boi", amount: 11 },
    { value: "Topher", amount: 11 },
    { value: "Tarby", amount: 11 },
    { value: "CaptMike", amount: 11 },
    { value: "rolle63", amount: 11 },
    { value: "CrescentWolf", amount: 11 },
    { value: "Postwar Vandal", amount: 11 },
    { value: "CajernSpice", amount: 11 },
    { value: "Tnx_Bayres", amount: 11 },
    { value: "FeuerGolem®", amount: 11 },
    { value: "Xo", amount: 11 },
    { value: "A_Vodka", amount: 11 },
    { value: "Wilk,u", amount: 11 },
    { value: "gn33101", amount: 11 },
    { value: "Grimm", amount: 11 },
    { value: "Citra Joe", amount: 11 },
    { value: "GeneralWiggin", amount: 11 },
    { value: "Stragerd", amount: 11 },
    { value: "taeles", amount: 11 },
    { value: "Garviel Stoker", amount: 11 },
    { value: "Kivister", amount: 11 },
    { value: "Joe3020", amount: 11 },
    { value: "[W4EV] Shiro Kitsune", amount: 11 },
    { value: "DarkPhoenix422", amount: 11 },
    { value: "SpiritSVK", amount: 11 },
    { value: "Sqirt", amount: 11 },
    { value: "COR Colin", amount: 11 },
    { value: "Noir", amount: 11 },
    { value: "vince.t", amount: 11 },
    { value: "Zon", amount: 11 },
    { value: "SuperScarab120", amount: 11 },
    { value: "ChronoSt0rm", amount: 11 },
    { value: "Aftermarket Player", amount: 11 },
    { value: "Agaster", amount: 11 },
    { value: "Stevenbeats1", amount: 11 },
    { value: "Mogol", amount: 11 },
    { value: "Thorgallsen", amount: 11 },
    { value: "mrkaho", amount: 11 },
    { value: "Remote-A-Troll", amount: 11 },
    { value: "KentiTiger", amount: 11 },
    { value: "Bruxel", amount: 11 },
    { value: "avrocf105", amount: 11 },
    { value: "TiggilerZ", amount: 11 },
    { value: "BEEESSS", amount: 11 },
    { value: "Lemon", amount: 11 },
    { value: "Sinxar", amount: 11 },
    { value: "FiveSecondsIsAYoke", amount: 11 },
    { value: "Infinity", amount: 10 },
    { value: "Aediway", amount: 10 },
    { value: "MACMAN2003", amount: 10 },
    { value: "Swol Shaggy", amount: 10 },
    { value: "Cryptic Zoroark", amount: 10 },
    { value: "Timely", amount: 10 },
    { value: "Vew", amount: 10 },
    { value: ".Maverick", amount: 10 },
    { value: "SailorLunar", amount: 10 },
    { value: "KMax", amount: 10 },
    { value: "Baba Yaga", amount: 10 },
    { value: "THE kilroy", amount: 10 },
    { value: "Coronivus", amount: 10 },
    { value: "Elliott", amount: 10 },
    { value: "Mr Unicorn", amount: 10 },
    { value: "Pirate", amount: 10 },
    { value: "Flamenaruto86", amount: 10 },
    { value: "Dr.Damage", amount: 10 },
    { value: "Alazar", amount: 10 },
    { value: "longbow69", amount: 10 },
    { value: "Urn", amount: 10 },
    { value: "wonderoveryonder04", amount: 10 },
    { value: "mcbobbo", amount: 10 },
    { value: "Gummi", amount: 10 },
    { value: "Skippy", amount: 10 },
    { value: "wotan111", amount: 10 },
    { value: "Papa Jefe", amount: 10 },
    { value: "SKX-Mo", amount: 10 },
    { value: "loloedok911", amount: 10 },
    { value: "iksmo", amount: 10 },
    { value: "Juan Perez de la Rosa", amount: 10 },
    { value: "Tokyo Jones", amount: 10 },
    { value: "Huntszy", amount: 10 },
    { value: "-YURIA-", amount: 10 },
    { value: "420loaded", amount: 10 },
    { value: "coltcoyote", amount: 10 },
    { value: "Charles Montgomery Burns", amount: 10 },
    { value: "Devin", amount: 10 },
    { value: "oOFirstyOo", amount: 10 },
    { value: "Carolus Rex", amount: 10 },
    { value: "FRANCK", amount: 10 },
    { value: "Silver", amount: 10 },
    { value: "Yakobe", amount: 10 },
    { value: "Mustard Chuck", amount: 10 },
    { value: "Razgriz", amount: 10 },
    { value: "vikinglier", amount: 10 },
    { value: "Stevee", amount: 10 },
    { value: "minoes", amount: 10 },
    { value: "差点没死成", amount: 10 },
    { value: "Danny C 301", amount: 10 },
    { value: "runedian", amount: 10 },
    { value: "Conservative,Christian,GunOwner", amount: 10 },
    { value: "akaAlex", amount: 10 },
    { value: "[Omega]", amount: 10 },
    { value: "WordBurglar", amount: 10 },
    { value: "ComradeWinston", amount: 10 },
    { value: "GRIN E", amount: 10 },
    { value: "Dawny", amount: 10 },
    { value: "danhayes3008", amount: 10 },
    { value: "Dog God", amount: 10 },
    { value: "T7", amount: 10 },
    { value: "Sumyjkl", amount: 10 },
    { value: "CornishGamer", amount: 10 },
    { value: "Makabre", amount: 10 },
    { value: "Dzheff", amount: 10 },
    { value: "Nooby", amount: 10 },
    { value: "Lockleed", amount: 10 },
    { value: "Blake Alexander Terida", amount: 10 },
    { value: "maxwilliam2003", amount: 10 },
    { value: "Bronko Kulicka", amount: 10 },
    { value: "Snugglez", amount: 10 },
    { value: "Xenolurker", amount: 10 },
    { value: "Whitehawk", amount: 10 },
    { value: "Shawn1563", amount: 10 },
    { value: "BeeSkee", amount: 10 },
    { value: "StevieWundaBred", amount: 10 },
    { value: "babeyblueyez04", amount: 10 },
    { value: "JAMESTHEKILLER!", amount: 10 },
    { value: "LДZУCФLLIИДΓФЯ", amount: 10 },
    { value: "Talon_65", amount: 10 },
    { value: "NebelFir", amount: 10 },
    { value: "FoeHammer_E419", amount: 10 },
    { value: "Dark Lord", amount: 10 },
    { value: "Biomechannibal", amount: 10 },
    { value: "~~Lars~~", amount: 10 },
    { value: "DiveBomber", amount: 10 },
    { value: "trollinator5729", amount: 10 },
    { value: "Lak´ech", amount: 10 },
    { value: "Vulpes", amount: 10 },
    { value: "SpartacusV", amount: 10 },
    { value: "Keroro Gunstar", amount: 10 },
    { value: "JoshPiper", amount: 10 },
    { value: "Puck", amount: 10 },
    { value: "True Quark", amount: 10 },
    { value: "Hampfrey", amount: 10 },
    { value: "Mouse", amount: 10 },
    { value: "Archan79", amount: 10 },
    { value: "Ivral Do ", amount: 10 },
    { value: "HAMMERFALL314", amount: 10 },
    { value: "AcuvaDisto", amount: 10 },
    { value: "Lone-Raven-Knight", amount: 10 },
    { value: "Praefectus-D | Ibra", amount: 10 },
    { value: "Bibs Kartouch", amount: 10 },
    { value: "RoastToast777", amount: 10 },
    { value: "shadowdargonRU", amount: 10 },
    { value: "Neonin", amount: 10 },
    { value: "heartofachampion2006", amount: 10 },
    { value: "dark", amount: 10 },
    { value: "Smildger", amount: 10 },
    { value: "neophyteg4mer", amount: 10 },
    { value: "FlamE", amount: 10 },
    { value: "SYMPA TA ROBE!!!!", amount: 10 },
    { value: "csokiturmix96", amount: 10 },
    { value: "Sop1130", amount: 10 },
    { value: "romstef", amount: 10 },
    { value: "Ye olde Dutch boi", amount: 10 },
    { value: "Gepizi Rader", amount: 10 },
    { value: "Vulkan", amount: 10 },
    { value: "Radio", amount: 10 },
    { value: "Captain Arcan", amount: 10 },
    { value: "ZwERG", amount: 10 },
    { value: "Bob-san", amount: 10 },
    { value: "Aunderis", amount: 10 },
    { value: "Spartiate", amount: 10 },
    { value: "Knowbotty", amount: 10 },
    { value: "Victory .CO", amount: 10 },
    { value: "Jalisurr", amount: 10 },
    { value: "0310njs", amount: 10 },
    { value: "battlecattle", amount: 10 },
    { value: "Diman Patrusheff", amount: 10 },
    { value: "Rudolf", amount: 10 },
    { value: "Jentek", amount: 10 },
    { value: "cypher", amount: 10 },
    { value: "Cheshmarine", amount: 10 },
    { value: "Peacemoon", amount: 10 },
    { value: "Striker", amount: 10 },
    { value: "Azr", amount: 10 },
    { value: "Commander Llewellyn", amount: 10 },
    { value: "Templar", amount: 10 },
    { value: "Quizitor", amount: 10 },
    { value: "APKAXEH", amount: 10 },
    { value: "ddDeath_666", amount: 10 },
    { value: "domburrows.95", amount: 10 },
    { value: "Voron", amount: 10 },
    { value: "Therow", amount: 10 },
    { value: "TESLA", amount: 10 },
    { value: "Crazeyfrog001", amount: 10 },
    { value: "Dark", amount: 10 },
    { value: "Ma.reyachi", amount: 10 },
    { value: "Hans", amount: 10 },
    { value: "[1stGA B3]Rct.Robert E.Lee", amount: 10 },
    { value: "Ubikjam", amount: 10 },
    { value: "YINKY", amount: 10 },
    { value: "piddlefoot", amount: 10 },
    { value: "Neoaptic", amount: 10 },
    { value: "saintxlive", amount: 10 },
    { value: "big smelly willy", amount: 10 },
    { value: "Mr. N00b", amount: 10 },
    { value: "[H] MeisterKeen", amount: 10 },
    { value: "Viktor", amount: 10 },
    { value: "sphere.d.by", amount: 10 },
    { value: "Shat", amount: 10 },
    { value: "NeoValkyrion", amount: 10 },
    { value: "TOG | SaintGrey", amount: 10 },
    { value: "Kropek", amount: 10 },
    { value: "Mackinaw", amount: 10 },
    { value: "VanuBaguio", amount: 10 },
    { value: "levi1659", amount: 10 },
    { value: "HawkeyePC", amount: 10 },
    { value: "Junior Patrick", amount: 10 },
    { value: "TumorSVT", amount: 10 },
    { value: "CannonFodderMK4", amount: 10 },
    { value: "[℘] Sarven", amount: 10 },
    { value: "ShiKmon", amount: 10 },
    { value: "Knightrider", amount: 10 },
    { value: "TheBlueMarauder", amount: 10 },
    { value: "Tony", amount: 10 },
    { value: "GrayETC", amount: 10 },
    { value: "Guardian", amount: 10 },
    { value: "Dittle", amount: 10 },
    { value: "migviola", amount: 10 },
    { value: "Niner", amount: 10 },
    { value: "The Black Muse", amount: 10 },
    { value: "Kibus Letus", amount: 10 },
    { value: "Leaving Destiny", amount: 10 },
    { value: "Dolpenguin", amount: 10 },
    { value: "Provo", amount: 10 },
    { value: "Cerafim", amount: 10 },
    { value: "DrREDST0NE", amount: 10 },
    { value: "Garry Windu", amount: 10 },
    { value: "DoUKnowTheWay", amount: 10 },
    { value: "FlamingNinja", amount: 10 },
    { value: "Eingeborene", amount: 10 },
    { value: "8_", amount: 10 },
    { value: "VOYAKA", amount: 10 },
    { value: "AdeKvatt", amount: 10 },
    { value: "QC | Phantom", amount: 10 },
    { value: "VDG", amount: 10 },
    { value: "红鲤鱼绿鲤鱼与驴", amount: 10 },
    { value: "The Darkness", amount: 10 },
    { value: "sithtrooper", amount: 10 },
    { value: "NYVS", amount: 10 },
    { value: "Snaegon", amount: 10 },
    { value: "CaptainShack", amount: 10 },
    { value: "Deadstatic", amount: 10 },
    { value: "Sprinkles", amount: 10 },
    { value: "-[FF]-Ace_ofChaos", amount: 10 },
    { value: "DragonGod", amount: 10 },
    { value: "Gravitywell420", amount: 10 },
    { value: "Splattercaster", amount: 10 },
    { value: "ScotsDragon", amount: 10 },
    { value: "Ivan", amount: 10 },
    { value: "Bolsa de pinzas", amount: 10 },
    { value: "xXAmaroqXx", amount: 10 },
    { value: "DarthWormee", amount: 10 },
    { value: "TheBlueGamer(DK)", amount: 10 },
    { value: "Boldro", amount: 10 },
    { value: "WallOfScience", amount: 10 },
    { value: "420ninja222", amount: 10 },
    { value: "Snakey", amount: 10 },
    { value: "Garrett", amount: 10 },
    { value: "103 | Sam", amount: 10 },
    { value: "ShuDrix", amount: 10 },
    { value: "Thales", amount: 10 },
    { value: "-Caranteeni-", amount: 10 },
    { value: "Auto noob", amount: 10 },
    { value: "Woopsious", amount: 10 },
    { value: "FireManDan", amount: 10 },
    { value: "Borkborks", amount: 10 },
    { value: "3071277307", amount: 10 },
    { value: "J-Limited", amount: 10 },
    { value: "NeverSayDie", amount: 10 },
    { value: "聆听疯狂的耳语", amount: 10 },
    { value: "Добрый Пират", amount: 10 },
    { value: "goldfiction", amount: 10 },
    { value: "Sir Humphrey Appleby", amount: 10 },
    { value: "Notspeedy", amount: 10 },
    { value: "Spanker", amount: 10 },
    { value: "Magic Space Pupper", amount: 10 },
    { value: "Venator", amount: 10 },
    { value: "Ragnos", amount: 10 },
    { value: "Jesper-Nybo", amount: 10 },
    { value: "Woftam", amount: 10 },
    { value: "bub1881", amount: 10 },
    { value: "sebastianhampel1", amount: 10 },
    { value: "Heartless Zealot", amount: 10 },
    { value: "Almirante Orlock", amount: 10 },
    { value: "PhonierDeluxe", amount: 10 },
    { value: "mikasashafan", amount: 10 },
    { value: "chrissyno", amount: 10 },
    { value: "[TSS]Pegasus47", amount: 10 },
    { value: "Chabin", amount: 10 },
    { value: "Kastenessen", amount: 10 },
    { value: "Fixguard", amount: 10 },
    { value: "Rhoke", amount: 10 },
    { value: "Khrono McLurvin", amount: 10 },
    { value: "[USGB]-FishHead", amount: 10 },
    { value: "hundreds dead", amount: 10 },
    { value: "Koinzell || Souza", amount: 10 },
    { value: "Baconblitz", amount: 10 },
    { value: "Gameomaster1012", amount: 10 },
    { value: "Lucifer Morningstar", amount: 10 },
    { value: "[TLOD] Bush Yowie", amount: 10 },
    { value: "VapeTrainGaming", amount: 10 },
    { value: "La Chaise", amount: 10 },
    { value: "xlodx", amount: 10 },
    { value: "Zero_Sen", amount: 10 },
    { value: "Squid", amount: 10 },
    { value: "ShadowZero", amount: 10 },
    { value: "Morphologis", amount: 10 },
    { value: "Cpt. T. Solar", amount: 10 },
    { value: "LittleNekoTerra", amount: 10 },
    { value: "yeetabix", amount: 10 },
    { value: "Burkey", amount: 10 },
    { value: "Everdro1d", amount: 10 },
    { value: "JonShard", amount: 10 },
    { value: "toys5342", amount: 10 },
    { value: "Сгущёнка ГОСТ 31688", amount: 10 },
    { value: "p3st|cIdE", amount: 10 },
]
