name: S3 Deploy
on:
  push:
    branches:
      - main

jobs:
  deploy_web_production:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
        - uses: actions/checkout@v3

        - name: Install dependencies
          working-directory: ./workspaces/app
          run: yarn

        - name: Package
          working-directory: ./workspaces/app
          run: yarn package:prod

        - name: Deploy
          uses: reggionick/s3-deploy@v3
          with:
            folder: ./workspaces/app/dist
            bucket: s3://spaceengineerspraisal.net
            bucket-region: eu-west-1
            dist-id: ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }}
            invalidation: /
            delete-removed: true
            no-cache: true
            private: true
            filesToInclude: ".*/*,*/*,**"
